/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CamadaApresentacao;

import Controller.ClienteController;
import java.time.Instant;
import java.time.LocalDate;
import java.util.Date;
import javax.swing.JOptionPane;
import util.SystemControl;
import util.mensagens;

/**
 *
 * @author 吉野　廉
 * @author 阿武隈
 * @author 長門
 * @author 大和
 */
public class CadastroCliente extends javax.swing.JDialog {

    private final SystemControl sc = new SystemControl();
    private final mensagens m = new mensagens();
    private final ClienteController cc = new ClienteController();
    float x, y;
    boolean flagG;
    
    public CadastroCliente(java.awt.Frame parent, boolean modal) 
    {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        jLabel15.setVisible(false);
        txtcli_datac.setVisible(false);
        txtcid_codigo.setVisible(false);
        btnNovo.setName("btnNovo");
        btnAlterar.setName("btnAlterar");
        btnCancelar.setName("btnCancelar");
        btnExcluir.setName("btnExcluir");
        btnGravar.setName("btnGravar");
        btnLocalizar.setName("btnLocalizar");
        btnaddCidade.setName("btnaddCidade");
        btnaddEstado.setName("btnaddEstado");
        btnSair.setName("btnSair");
        x = panefisica.getAlignmentX();
        y = panefisica.getAlignmentY();
        jPanel2.setAlignmentX(x);
      //  jPanel2.setAlignmentY(y-5);
        this.setSize(this.getWidth(), this.getHeight()-115);
        sc.HabilityComponents(jPanel1.getComponents(), false);
        sc.HabilityComponents(panefisica.getComponents(), false);
        sc.HabilityComponents(panejuridica.getComponents(), false);
        sc.Initialize(jPanel2.getComponents()); 
        rbfisica.setSelected(true);
        CarregaEstado();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtcli_cod = new javax.swing.JTextField();
        rbfisica = new javax.swing.JRadioButton();
        rbjuridica = new javax.swing.JRadioButton();
        txtcli_nome = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cbuf = new javax.swing.JComboBox<>();
        btnaddEstado = new javax.swing.JButton();
        cbcidade = new javax.swing.JComboBox<>();
        btnaddCidade = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtcli_endereco = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtcli_numero = new javax.swing.JTextField();
        txtcli_cep = new javax.swing.JFormattedTextField();
        txtcli_complemento = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtcli_telefone = new javax.swing.JFormattedTextField();
        jLabel10 = new javax.swing.JLabel();
        txtcli_telefone1 = new javax.swing.JFormattedTextField();
        jLabel15 = new javax.swing.JLabel();
        txtcid_codigo = new javax.swing.JTextField();
        txtEmail = new br.com.ikeda.beans.jTextFieldEmail();
        txtcli_datac = new br.com.marciorl.beans.DateChooser();
        panefisica = new javax.swing.JPanel();
        txtcli_cpf = new javax.swing.JFormattedTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtcli_rg = new javax.swing.JFormattedTextField();
        jLabel14 = new javax.swing.JLabel();
        txtcli_orgEmi = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtcli_datanasc = new br.com.marciorl.beans.DateChooser();
        panejuridica = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtcli_rs = new javax.swing.JTextField();
        txtcli_cnpj = new br.com.ikeda.beans.jFormatTextCnpj();
        txtcli_ie = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnNovo = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnGravar = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnLocalizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setText("Codigo:");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("Nome/Firma:");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("Cidade:");

        txtcli_cod.setEditable(false);
        txtcli_cod.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtcli_cod.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtcli_codFocusLost(evt);
            }
        });

        rbfisica.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        rbfisica.setText("Pessoa Fisica");
        rbfisica.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rbfisicaStateChanged(evt);
            }
        });

        rbjuridica.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        rbjuridica.setText("Pessoa Juridica");
        rbjuridica.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rbjuridicaStateChanged(evt);
            }
        });

        txtcli_nome.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("Estado:");

        cbuf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cbufFocusLost(evt);
            }
        });

        btnaddEstado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Novo 16.png"))); // NOI18N
        btnaddEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddEstadoActionPerformed(evt);
            }
        });

        cbcidade.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cbcidadeFocusLost(evt);
            }
        });

        btnaddCidade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Novo 16.png"))); // NOI18N
        btnaddCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddCidadeActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setText("Endereço:");

        txtcli_endereco.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setText("Número:");

        txtcli_numero.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        try {
            txtcli_cep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtcli_cep.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        txtcli_complemento.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel7.setText("Complemento:");

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setText("CEP:");

        jLabel9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel9.setText("Telefone:");

        try {
            txtcli_telefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel10.setText("Celular:");

        try {
            txtcli_telefone1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel15.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel15.setText("Data de Cadastro:");

        txtcid_codigo.setEditable(false);
        txtcid_codigo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtcid_codigo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtcid_codigoFocusLost(evt);
            }
        });

        txtcli_datac.setEditable(false);

        panefisica.setBackground(new java.awt.Color(255, 255, 255));
        panefisica.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Fisica", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 12))); // NOI18N

        try {
            txtcli_cpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###/##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtcli_cpf.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel12.setText("CPF:");

        jLabel13.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel13.setText("RG:");

        try {
            txtcli_rg.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###-A")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtcli_rg.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLabel14.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel14.setText("Örg. Emissor:");

        txtcli_orgEmi.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLabel17.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel17.setText("Data de Nascimento:");

        javax.swing.GroupLayout panefisicaLayout = new javax.swing.GroupLayout(panefisica);
        panefisica.setLayout(panefisicaLayout);
        panefisicaLayout.setHorizontalGroup(
            panefisicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panefisicaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panefisicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panefisicaLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtcli_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtcli_rg, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtcli_orgEmi, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panefisicaLayout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtcli_datanasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panefisicaLayout.setVerticalGroup(
            panefisicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panefisicaLayout.createSequentialGroup()
                .addGroup(panefisicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcli_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(txtcli_rg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(txtcli_orgEmi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panefisicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txtcli_datanasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panejuridica.setBackground(new java.awt.Color(255, 255, 255));
        panejuridica.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Juridica", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 12))); // NOI18N

        jLabel16.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel16.setText("CNPJ:");

        jLabel18.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel18.setText("Inscrição Estadual:");

        jLabel19.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel19.setText("Razão Social:");

        txtcli_rs.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        txtcli_ie.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        javax.swing.GroupLayout panejuridicaLayout = new javax.swing.GroupLayout(panejuridica);
        panejuridica.setLayout(panejuridicaLayout);
        panejuridicaLayout.setHorizontalGroup(
            panejuridicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panejuridicaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panejuridicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panejuridicaLayout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtcli_cnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtcli_ie, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panejuridicaLayout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtcli_rs)))
                .addContainerGap())
        );
        panejuridicaLayout.setVerticalGroup(
            panejuridicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panejuridicaLayout.createSequentialGroup()
                .addGroup(panejuridicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(txtcli_rs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(panejuridicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel18)
                    .addComponent(txtcli_cnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcli_ie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 1, Short.MAX_VALUE))
        );

        jLabel11.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel11.setText("e-mail:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panefisica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtcli_endereco))
                    .addComponent(panejuridica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbuf, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnaddEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbcidade, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnaddCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtcli_nome))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtcli_cod, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48)
                                .addComponent(rbfisica)
                                .addGap(18, 18, 18)
                                .addComponent(rbjuridica))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtcli_numero, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtcli_cep, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtcli_complemento, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtcli_telefone, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtcli_telefone1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel15)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtcli_datac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                        .addComponent(txtcid_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtcli_cod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbfisica)
                    .addComponent(rbjuridica)
                    .addComponent(txtcid_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtcli_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4)
                                .addComponent(cbuf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cbcidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnaddCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtcli_endereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnaddEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(txtcli_cep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7)
                        .addComponent(txtcli_complemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(txtcli_numero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtcli_telefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(txtcli_telefone1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(txtcli_datac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(7, 7, 7)
                .addComponent(panefisica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panejuridica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnNovo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Gravar16.png"))); // NOI18N
        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnAlterar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Alterar16.png"))); // NOI18N
        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnExcluir.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Excluir16.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnGravar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnGravar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Gravar16.png"))); // NOI18N
        btnGravar.setText("Gravar");
        btnGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGravarActionPerformed(evt);
            }
        });

        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Sair.png"))); // NOI18N
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Cancelar16.png.jpg"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnLocalizar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnLocalizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Localizar 16.png"))); // NOI18N
        btnLocalizar.setText("Localizar");
        btnLocalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLocalizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLocalizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGravar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGravar, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnLocalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        setBounds(0, 0, 779, 650);
    }// </editor-fold>//GEN-END:initComponents

    private void txtcli_codFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtcli_codFocusLost
      if(!txtcli_cod.getText().equals("0"))
      {
          if(cc.buscaClienteCodigo(Integer.parseInt(txtcli_cod.getText())) != null)
          {
              if(cc.getC().getStatus())
              {
                cc.carregaFisica(cc.getC().getCodigo());
                cc.carregaJuridica(cc.getC().getCodigo());
                txtEmail.setText(cc.getC().getEmail());
                txtcli_cod.setText(""+cc.getC().getCodigo());
                txtcli_cep.setText(cc.getC().getCep());
                txtcli_complemento.setText(cc.getC().getComplemento());
                txtcli_datac.setText(""+cc.getC().getDataC());
                txtcli_endereco.setText(cc.getC().getEndereco());
                txtcli_nome.setText(cc.getC().getNome());
                txtcli_numero.setText(""+cc.getC().getNunero());
                txtcli_telefone.setText(cc.getC().getTelefone());
                txtcli_telefone1.setText(cc.getC().getCelular());

                if(cc.getC().getCpf() != null)
                {
                    rbfisica.setSelected(true);
                    txtcli_cpf.setText(cc.getC().getCpf());
                    txtcli_rg.setText(cc.getC().getRg());
                    txtcli_orgEmi.setText(cc.getC().getOrg_insc());
                    txtcli_datanasc.setData(cc.getC().getDataNasc());
                }
                else
                {
                    rbjuridica.setSelected(true);
                    txtcli_rs.setText(cc.getC().getRazasoci());
                    txtcli_cnpj.setText(cc.getC().getCnpj());
                    txtcli_ie.setText(cc.getC().getOrg_insc());
                }

                cbuf.setSelectedItem(cc.getC().getCid().getE().getSigla());
                cc.CarregaCidade(cbcidade, (String) cbuf.getSelectedItem());
                cbcidade.setSelectedItem(cc.getC().getCid().getNome());
                txtcid_codigo.setText(""+cc.getC().getCid().getCodigo());
                sc.Alter(jPanel2.getComponents());
              }
              else
              {
                  if(JOptionPane.showConfirmDialog(null, "Este cliente não esta Ativo, Deseja Ativar novamente?", "", JOptionPane.INFORMATION_MESSAGE) == JOptionPane.YES_OPTION)
                  {
                      cc.recuperar();
                      m.InformationMessage("Ativado com sucesso", "Informação");
                      limpar();
                  }
                  else
                  {
                    cc.carregaFisica(cc.getC().getCodigo());
                    cc.carregaJuridica(cc.getC().getCodigo());
                    txtEmail.setText(cc.getC().getEmail());
                    txtcli_cod.setText(""+cc.getC().getCodigo());
                    txtcli_cep.setText(cc.getC().getCep());
                    txtcli_complemento.setText(cc.getC().getComplemento());
                    txtcli_datac.setText(""+cc.getC().getDataC());
                    txtcli_endereco.setText(cc.getC().getEndereco());
                    txtcli_nome.setText(cc.getC().getNome());
                    txtcli_numero.setText(""+cc.getC().getNunero());
                    txtcli_telefone.setText(cc.getC().getTelefone());
                    txtcli_telefone1.setText(cc.getC().getCelular());

                    if(cc.getC().getCpf() != null)
                    {
                        rbfisica.setSelected(true);
                        txtcli_cpf.setText(cc.getC().getCpf());
                        txtcli_rg.setText(cc.getC().getRg());
                        txtcli_orgEmi.setText(cc.getC().getOrg_insc());
                        txtcli_datanasc.setData(cc.getC().getDataNasc());
                    }
                    else
                    {
                        rbjuridica.setSelected(true);
                        txtcli_rs.setText(cc.getC().getRazasoci());
                        txtcli_cnpj.setText(cc.getC().getCnpj());
                        txtcli_ie.setText(cc.getC().getOrg_insc());
                    }

                    cbuf.setSelectedItem(cc.getC().getCid().getE().getSigla());
                    cc.CarregaCidade(cbcidade, (String) cbuf.getSelectedItem());
                    cbcidade.setSelectedItem(cc.getC().getCid().getNome());
                    txtcid_codigo.setText(""+cc.getC().getCid().getCodigo());
                    sc.Alter(jPanel2.getComponents());
                  }
              }
          }
      }
    }//GEN-LAST:event_txtcli_codFocusLost

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        sc.HabilityComponents(jPanel1.getComponents(), true);
        sc.HabilityComponents(panefisica.getComponents(), true);
        sc.HabilityComponents(panejuridica.getComponents(), true);
        sc.Edity(jPanel2.getComponents()); 
        txtcli_cod.setText("0");
        flagG = true;
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        sc.HabilityComponents(jPanel1.getComponents(), true);
        sc.HabilityComponents(panefisica.getComponents(), true);
        sc.HabilityComponents(panejuridica.getComponents(), true);
        sc.Edity(jPanel2.getComponents()); 
        flagG = false;
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        if(JOptionPane.showConfirmDialog(this, "Deseja realmente excluir este cliente?", "Atenção", JOptionPane.WARNING_MESSAGE) == JOptionPane.YES_OPTION)
        {
            cc.excluir(Integer.parseInt(txtcli_cod.getText()));
            limpar();
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
    limpar();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnLocalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLocalizarActionPerformed
        ConsultaPadrao consFuncionario = new ConsultaPadrao(null, true);
        String[] vet = new String[3];
        vet[0] = "Nome";
        vet[1] = "CPF";
        vet[2] = "CNPJ";
        consFuncionario.configuraOpcoes(vet, 3, 0, "Cliente", false);
        consFuncionario.verificaconsulta(true);
        consFuncionario.setVisible(true);
        if (consFuncionario.getCodigo() != 0)
        {
            txtcli_cod.setText(""+consFuncionario.getCodigo());
            consFuncionario.dispose();
            txtcli_codFocusLost(null);
        }
        else
        {
            consFuncionario.dispose();
            btnLocalizar.requestFocus();
        }
    }//GEN-LAST:event_btnLocalizarActionPerformed

    private void btnGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGravarActionPerformed
        String c;
        c = txtcli_orgEmi.getText().equals("") ? txtcli_ie.getText() : txtcli_orgEmi.getText();
        boolean flag = rbfisica.isSelected();
        switch(cc.validar(txtcli_cod.getText(), txtcid_codigo.getText(), txtcli_nome.getText(), txtcli_endereco.getText(), txtcli_numero.getText(), txtcli_complemento.getText(), txtcli_cep.getText(), txtcli_telefone.getText(), txtcli_telefone1.getText(), txtEmail.getText(), txtcli_cpf.getText(), txtcli_rg.getText(), c, txtcli_datanasc.getData(), txtcli_rs.getText(), txtcli_cnpj.getText(), flag))
        {//              String codigo, String cidade,                     String nome, String endereco,                    String numero,          String complemento, String cep,                 String telefone, String celular,                                String email, String cpf, String rg, String orgemi_insc,                                                                                    LocalDate dataNasc, String razasoci, String cnpj, boolean flag
            case 1: JOptionPane.showMessageDialog(this, "Codigo Invalido","Alerta", JOptionPane.WARNING_MESSAGE); break;
            case 2: JOptionPane.showMessageDialog(this, "Informe o Nome","Alerta", JOptionPane.WARNING_MESSAGE);
            txtcli_nome.requestFocus(); break;
            case 7:
                if(flag)
                {
                    JOptionPane.showMessageDialog(this, "Informe o Orgão emissor","Alerta", JOptionPane.WARNING_MESSAGE);
                    txtcli_orgEmi.requestFocus();
                }
                else
                {
                    JOptionPane.showMessageDialog(this, "Informe Inscrição Estadual","Alerta", JOptionPane.WARNING_MESSAGE);
                    txtcli_ie.requestFocus();
                }

            break;
            case 8:
                if(flag)
                {
                    JOptionPane.showMessageDialog(this, "O tamanho do Orgão emissor deve ser 2 caracteres","Alerta", JOptionPane.WARNING_MESSAGE);
                    txtcli_orgEmi.requestFocus();
                }
                else
                {
                    JOptionPane.showMessageDialog(this, "O tamanho da Inscrição Estadual deve ser 2 caracteres","Alerta", JOptionPane.WARNING_MESSAGE);
                    txtcli_ie.requestFocus();
                }
            break;
            case 9:
            JOptionPane.showMessageDialog(this, "Informe o endereço","Alerta", JOptionPane.WARNING_MESSAGE);
            txtcli_endereco.requestFocus();
            break;
            case 10:
            JOptionPane.showMessageDialog(this, "Inforem o Número","Alerta", JOptionPane.WARNING_MESSAGE);
            txtcli_numero.requestFocus();
            break;
            case 11:
            JOptionPane.showMessageDialog(this, "Informe Número","Alerta", JOptionPane.WARNING_MESSAGE);
            txtcli_numero.requestFocus();
            txtcli_numero.setText("");
            break;
            case 12:
            JOptionPane.showMessageDialog(this, "Inforem pelomenos o celular ou telefone","Alerta", JOptionPane.WARNING_MESSAGE);
            txtcli_telefone.requestFocus();
            break;
            case 13:
            JOptionPane.showMessageDialog(this, "Inforem o CEP","Alerta", JOptionPane.WARNING_MESSAGE);
            txtcli_cep.requestFocus();
            break;
            case 14:
            JOptionPane.showMessageDialog(this, "E-Mail Invalido","Alerta", JOptionPane.WARNING_MESSAGE);
            txtEmail.requestFocus();
            break;
            case 15:
            JOptionPane.showMessageDialog(this, "Inforem o CPF","Alerta", JOptionPane.WARNING_MESSAGE);
            txtcli_cpf.requestFocus();
            break;
            case 16:
            JOptionPane.showMessageDialog(this, "Inforem o RG","Alerta", JOptionPane.WARNING_MESSAGE);
            txtcli_rg.requestFocus();
            break;
            case 17:
            JOptionPane.showMessageDialog(this, "Inforem uma data menor que a data de hoje","Alerta", JOptionPane.WARNING_MESSAGE);
            txtcli_datanasc.requestFocus();
            break;
            case 18:
            JOptionPane.showMessageDialog(this, "Inforem o CNPJ","Alerta", JOptionPane.WARNING_MESSAGE);
            txtcli_cnpj.requestFocus();
            break;
            case 19:
            JOptionPane.showMessageDialog(this, "Inforem a Rasão Social","Alerta", JOptionPane.WARNING_MESSAGE);
            txtcli_rs.requestFocus();
            break;
            case 20:
                ClienteController cctemp = new ClienteController();
                cctemp.setC(cc.buscaVerifica()); 
                if(!cctemp.getC().getStatus())
                {
                    if(JOptionPane.showConfirmDialog(this, "CPF/CNPJ informado ja possui cadastro, porem esta desabilitado. Deseja Ativar?", "Atenção", JOptionPane.WARNING_MESSAGE) == JOptionPane.YES_OPTION)
                    {
                        if(cctemp.recuperar())
                        {
                            m.InformationMessage("Recuperado com sucesso!", "Informação");
                        }
                        else
                        {
                            m.InformationMessage("Erro ao recuperar", "Informação");
                        }
                    }
                    else
                    {
                        m.ErroMessage("Cliente ja cadastrado", "ERRO"); 
                    }
                }
                else
                {
                    m.ErroMessage("Cliente ja cadastrado", "ERRO"); 
                }
            break;
            default:
            if(cc.gravar())
            {
                if(cc.gravarSegundaParte(flagG))
                {
                    JOptionPane.showMessageDialog(this, "Gravado com sucesso!","Informação", JOptionPane.INFORMATION_MESSAGE);
                    limpar();                    
                }
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Erro ao Gravar","Erro", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnGravarActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void txtcid_codigoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtcid_codigoFocusLost
        // txtcli_cod.getText(), txtcid_codigo.getText(), txtcli_nome.getText(), txtcli_endereco.getText(), txtcli_numero.getText(), txtcli_complemento.getText(), txtcli_cep.getText(), txtcli_telefone.getText(), txtcli_telefone1.getText(), txtEmail.getText(), txtcli_cpf.getText(), txtcli_rg.getText(), c, LocalDate.parse((CharSequence) txtcli_datanasc.getValue()), txtcli_rs.getText(), txtcli_cnpj.getText(), flag
        if(!txtcli_cod.getText().equals("0"))//, combo box 
        {
            //busca
            txtcid_codigo.setText(""+cc.getC().getCid().getCodigo());
            txtcli_nome.setText(cc.getC().getNome());
            txtcli_endereco.setText(cc.getC().getEndereco());
            txtcli_numero.setText(""+cc.getC().getNunero());
            txtcli_complemento.setText(cc.getC().getComplemento());
            txtcli_cep.setText(cc.getC().getCep());
            txtcli_telefone.setText(cc.getC().getTelefone());
            txtcli_telefone1.setText(cc.getC().getCelular());
            txtEmail.setText(cc.getC().getEmail());
            txtcli_cpf.setText(cc.getC().getCpf());
            txtcli_rg.setText(cc.getC().getRg());
            txtcli_rs.setText(cc.getC().getRazasoci()); 
            txtcli_cnpj.setText(cc.getC().getCnpj());
            if(cc.getC().getCpf() == null)
            {
                txtcli_ie.setText(cc.getC().getOrg_insc());
                rbjuridica.setSelected(true);
            }
            else
            {
                txtcli_orgEmi.setText(cc.getC().getOrg_insc());
                rbfisica.setSelected(true);
            }
            String data = ""+cc.getC().getDataNasc();
            txtcli_datac.setData(Date.from(Instant.parse((CharSequence) data))); 
            cbuf.setSelectedItem(cc.getC().getCid().getE().getSigla());
            cbcidade.setSelectedItem(cc.getC().getCid().getNome()); 
        }
    }//GEN-LAST:event_txtcid_codigoFocusLost

    private void rbfisicaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rbfisicaStateChanged
    if(rbfisica.isSelected())
    {
        rbjuridica.setSelected(false);
        panefisica.setAlignmentX(x);
        panefisica.setAlignmentY(y);
        panefisica.setVisible(true);
        panejuridica.setVisible(false);
    }
    }//GEN-LAST:event_rbfisicaStateChanged

    private void rbjuridicaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rbjuridicaStateChanged
    if(rbjuridica.isSelected())
    {
        rbfisica.setSelected(false);
        panejuridica.setAlignmentX(x);
        panejuridica.setAlignmentY(y);
        panejuridica.setVisible(true);
        panefisica.setVisible(false);
    }
    }//GEN-LAST:event_rbjuridicaStateChanged

    private void btnaddEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddEstadoActionPerformed
        CadastroEstado frm = new CadastroEstado(null, true);
        frm.setVisible(true);
    }//GEN-LAST:event_btnaddEstadoActionPerformed

    private void btnaddCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddCidadeActionPerformed
        CadastroCidade frm = new CadastroCidade(null, true);
        frm.setVisible(true);
    }//GEN-LAST:event_btnaddCidadeActionPerformed

    private void cbufFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cbufFocusLost
      if(cbuf.getSelectedItem() != null)
        cc.CarregaCidade(cbcidade, (String) cbuf.getSelectedItem());
    }//GEN-LAST:event_cbufFocusLost

    private void cbcidadeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cbcidadeFocusLost
        if(cbcidade.getSelectedItem() != null)
            txtcid_codigo.setText(""+cc.buscaCodigoCidade((String)cbcidade.getSelectedItem(), (String)cbuf.getSelectedItem()));
    }//GEN-LAST:event_cbcidadeFocusLost

    private void limpar()
    {
        txtcli_cod.setText("");
        txtcli_cep.setText("");
        txtcli_cnpj.setText("");
        txtcli_complemento.setText("");
        txtcli_cpf.setText("");
        txtcli_datanasc.setData(Date.from(Instant.now()));
        txtcli_datanasc.setData(Date.from(Instant.now()));
        txtcli_ie.setText("");
        txtcli_nome.setText("");
        txtcli_numero.setText("");
        txtcli_orgEmi.setText("");
        txtcli_rg.setText("");
        txtcli_rs.setText("");
        txtcli_telefone.setText("");
        txtcli_telefone1.setText("");
        txtcli_endereco.setText("");
        txtEmail.setText("");
        cbuf.setSelectedIndex(0);
        cbcidade.removeAllItems();
        txtcid_codigo.setText("");
        
        sc.HabilityComponents(jPanel1.getComponents(), false);
        sc.HabilityComponents(panefisica.getComponents(), false);
        sc.HabilityComponents(panejuridica.getComponents(), false);
        sc.Initialize(jPanel2.getComponents()); 
    }
    
    private void CarregaEstado()
    {
        cc.CarregaEstado(this.cbuf);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnGravar;
    private javax.swing.JButton btnLocalizar;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnaddCidade;
    private javax.swing.JButton btnaddEstado;
    private javax.swing.JComboBox<String> cbcidade;
    private javax.swing.JComboBox<String> cbuf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel panefisica;
    private javax.swing.JPanel panejuridica;
    private javax.swing.JRadioButton rbfisica;
    private javax.swing.JRadioButton rbjuridica;
    private br.com.ikeda.beans.jTextFieldEmail txtEmail;
    private javax.swing.JTextField txtcid_codigo;
    private javax.swing.JFormattedTextField txtcli_cep;
    private br.com.ikeda.beans.jFormatTextCnpj txtcli_cnpj;
    private javax.swing.JTextField txtcli_cod;
    private javax.swing.JTextField txtcli_complemento;
    private javax.swing.JFormattedTextField txtcli_cpf;
    private br.com.marciorl.beans.DateChooser txtcli_datac;
    private br.com.marciorl.beans.DateChooser txtcli_datanasc;
    private javax.swing.JTextField txtcli_endereco;
    private javax.swing.JTextField txtcli_ie;
    private javax.swing.JTextField txtcli_nome;
    private javax.swing.JTextField txtcli_numero;
    private javax.swing.JTextField txtcli_orgEmi;
    private javax.swing.JFormattedTextField txtcli_rg;
    private javax.swing.JTextField txtcli_rs;
    private javax.swing.JFormattedTextField txtcli_telefone;
    private javax.swing.JFormattedTextField txtcli_telefone1;
    // End of variables declaration//GEN-END:variables
}
