/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CamadaApresentacao;
import java.applet.Applet;
import util.*;
import Controller.FuncionarioController;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author 吉野　廉
 * @author 羽根川　翼
 * @author モニカ
 * 
 * @author 弐条
 * @author 七草
 */
public class CadastroFuncionario extends javax.swing.JDialog {

    private final SystemControl sc = new SystemControl();
    private final mensagens m = new mensagens();
    private final FuncionarioController fc = new FuncionarioController();
    private int soma;
    private final boolean firstAccess;

    public CadastroFuncionario(java.awt.Frame parent, boolean modal, boolean firstAccess) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        txtCodigo.setEnabled(false);
        this.firstAccess = firstAccess;
        txtCaminho.setVisible(false);
        txtCodCid.setVisible(false);
        btnNovo.setName("btnNovo");
        btnAlterar.setName("btnAlterar");
        btnCancelar.setName("btnCancelar");
        btnExcluir.setName("btnExcluir");
        btnGravar.setName("btnGravar");
        btnLocalizar.setName("btnLocalizar");
        btnaddCidade.setName("btnaddCidade");
        btnSair.setName("btnSair");
        if(firstAccess)
        {
            sc.HabilityComponents(jPanel1.getComponents(), true);
            sc.HabilityComponents(jPanel4.getComponents(), true);
            sc.HabilityComponents(jPanel3.getComponents(), false);
            cbAdm.setSelected(true);
            soma = 64;
            sc.Edity(jPanel2.getComponents());
            txtCodigo.setText("0");
            btnCancelar.setEnabled(false);
            btnSair.setEnabled(false);
        }
        else
        {
            this.soma = 0;
            sc.HabilityComponents(jPanel1.getComponents(), false);
            sc.HabilityComponents(jPanel4.getComponents(), false);
            sc.HabilityComponents(jPanel3.getComponents(), false);
            sc.Initialize(jPanel2.getComponents());
            cbCadastro.setEnabled(false);
            cbConsulta.setEnabled(false);
            cbMovimentacao.setEnabled(false);
            cbRelatorio.setEnabled(false);
            cbAdm.setEnabled(false);
        }
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnaddCidade = new javax.swing.JButton();
        btnLocCidade = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtEndereco = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        txtComplemento = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtCep = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        txtTelefone = new javax.swing.JFormattedTextField();
        jLabel10 = new javax.swing.JLabel();
        txtCelular = new javax.swing.JFormattedTextField();
        txtCidade = new javax.swing.JTextField();
        txtUf = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtCpf = new javax.swing.JFormattedTextField();
        txtRg = new javax.swing.JFormattedTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtOrgemi = new javax.swing.JTextField();
        txtUsuario = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtSenha = new javax.swing.JPasswordField();
        jPanel3 = new javax.swing.JPanel();
        cbCadastro = new javax.swing.JCheckBox();
        cbConsulta = new javax.swing.JCheckBox();
        cbRelatorio = new javax.swing.JCheckBox();
        cbMovimentacao = new javax.swing.JCheckBox();
        cbAdm = new javax.swing.JCheckBox();
        jLNivelAtual = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lFoto = new javax.swing.JLabel();
        btnBuscaImg = new javax.swing.JButton();
        btnLimpaImg = new javax.swing.JButton();
        txtCaminho = new javax.swing.JTextField();
        txtCodCid = new javax.swing.JTextField();
        txtSenha1 = new javax.swing.JPasswordField();
        jLabel16 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnNovo = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnGravar = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnLocalizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setText("Codigo:");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("Nome:");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("Cidade:");

        txtCodigo.setEditable(false);
        txtCodigo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtCodigo.setName("txtCodigo"); // NOI18N
        txtCodigo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCodigoFocusLost(evt);
            }
        });

        txtNome.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("Estado:");

        btnaddCidade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Novo 16.png"))); // NOI18N
        btnaddCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddCidadeActionPerformed(evt);
            }
        });

        btnLocCidade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Localizar 16.png"))); // NOI18N
        btnLocCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLocCidadeActionPerformed(evt);
            }
        });
        btnLocCidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnLocCidadeKeyPressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setText("Endereço:");

        txtEndereco.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setText("Número:");

        txtNumero.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        txtComplemento.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel7.setText("Complemento:");

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setText("CEP:");

        try {
            txtCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCep.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel9.setText("Telefone:");

        try {
            txtTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel10.setText("Celular:");

        try {
            txtCelular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-#####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        txtCidade.setEditable(false);
        txtCidade.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        txtUf.setEditable(false);
        txtUf.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel12.setText("CPF:");

        try {
            txtCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###/##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCpf.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        try {
            txtRg.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###-A")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtRg.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel13.setText("RG:");

        jLabel14.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel14.setText("Örg. Emissor:");

        txtOrgemi.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        txtUsuario.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel11.setText("Usuario:");

        jLabel15.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel15.setText("Senha:");

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Nivel", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 11))); // NOI18N

        cbCadastro.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        cbCadastro.setText("Cadastro");
        cbCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCadastroActionPerformed(evt);
            }
        });

        cbConsulta.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        cbConsulta.setText("Consulta");
        cbConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbConsultaActionPerformed(evt);
            }
        });

        cbRelatorio.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        cbRelatorio.setText("Relatorio");
        cbRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbRelatorioActionPerformed(evt);
            }
        });

        cbMovimentacao.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        cbMovimentacao.setText("Movimentação");
        cbMovimentacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMovimentacaoActionPerformed(evt);
            }
        });

        cbAdm.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        cbAdm.setText("Administrador");
        cbAdm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAdmActionPerformed(evt);
            }
        });

        jLNivelAtual.setText("0");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbCadastro)
                .addGap(18, 18, 18)
                .addComponent(cbConsulta)
                .addGap(18, 18, 18)
                .addComponent(cbRelatorio)
                .addGap(18, 18, 18)
                .addComponent(cbMovimentacao)
                .addGap(18, 18, 18)
                .addComponent(cbAdm)
                .addGap(102, 102, 102)
                .addComponent(jLNivelAtual, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbCadastro)
                    .addComponent(cbConsulta)
                    .addComponent(cbRelatorio)
                    .addComponent(cbMovimentacao)
                    .addComponent(cbAdm)
                    .addComponent(jLNivelAtual))
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnBuscaImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Folder.png"))); // NOI18N
        btnBuscaImg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscaImgActionPerformed(evt);
            }
        });

        btnLimpaImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Excluir16.png"))); // NOI18N
        btnLimpaImg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpaImgActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lFoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btnBuscaImg, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnLimpaImg, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLimpaImg, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscaImg, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        txtCodCid.setEditable(false);
        txtCodCid.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtCodCid.setName("txtCodigo"); // NOI18N

        jLabel16.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel16.setText("Confirma Senha:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEndereco))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtUf, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCidade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnaddCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLocCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNome))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel11)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel15)
                                                .addGap(18, 18, 18)
                                                .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel16)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtSenha1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(jLabel12)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(33, 33, 33)
                                                        .addComponent(jLabel13)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(txtRg, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(jLabel14)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(txtOrgemi, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(jLabel6)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(39, 39, 39)
                                                        .addComponent(jLabel8)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(txtCep, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(39, 39, 39)
                                                        .addComponent(jLabel7)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(txtComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(jLabel9)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(jLabel10)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(76, 76, 76))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(txtCodCid, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                        .addComponent(txtCaminho, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 4, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCaminho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCodCid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(txtRg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(txtOrgemi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16)
                            .addComponent(txtSenha1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jLabel4)
                        .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtUf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnLocCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnaddCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(txtCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7)
                        .addComponent(txtComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnNovo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Novo 16.png"))); // NOI18N
        btnNovo.setText("Novo");
        btnNovo.setName("btnNovo"); // NOI18N
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnAlterar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Alterar16.png"))); // NOI18N
        btnAlterar.setText("Alterar");
        btnAlterar.setName("btnAlterar"); // NOI18N
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnExcluir.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Excluir16.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.setName("btnExcluir"); // NOI18N
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnGravar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnGravar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Gravar16.png"))); // NOI18N
        btnGravar.setText("Gravar");
        btnGravar.setName("btnGravar"); // NOI18N
        btnGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGravarActionPerformed(evt);
            }
        });

        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Sair.png"))); // NOI18N
        btnSair.setName("btnSair"); // NOI18N
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Cancelar16.png.jpg"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setName("btnCancelar"); // NOI18N
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnLocalizar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnLocalizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Localizar 16.png"))); // NOI18N
        btnLocalizar.setText("Localizar");
        btnLocalizar.setName("btnLocalizar"); // NOI18N
        btnLocalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLocalizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLocalizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGravar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGravar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAlterar, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                    .addComponent(btnNovo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLocalizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    
    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        sc.Edity(jPanel2.getComponents());
        sc.HabilityComponents(jPanel1.getComponents(), true);
        sc.HabilityComponents(jPanel3.getComponents(), true);
        sc.HabilityComponents(jPanel4.getComponents(), true);
        txtCodigo.setText("0");
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
    sc.Edity(jPanel2.getComponents());
    sc.HabilityComponents(jPanel1.getComponents(), true);    
    sc.HabilityComponents(jPanel3.getComponents(), true);
    sc.HabilityComponents(jPanel4.getComponents(), true);
    if(fc.checkADMCount() && fc.getFunc().getNivel() == 64) /// colocar uma outra checaem verificando o nivel dele se for iguala 64.
    {
        m.ErroMessage("Como existe apenas um Administrador, não sera permitido alterar o nivel", "Erro");
        sc.HabilityComponents(jPanel3.getComponents(), false);
        sc.HabilityComponents(jPanel3.getComponents(), false);
        sc.HabilityComponents(jPanel4.getComponents(), false);
    }
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        if(fc.checkADMCount() && cbAdm.isSelected())
        {
            m.ErroMessage("Nao pode demitido pelo fato de ter somente um Administrador", "Erro");
        }
        else
        {
            if(JOptionPane.showConfirmDialog(null, "Confirama a demição deste funcioanrio?", "Atenção", JOptionPane.INFORMATION_MESSAGE) == JOptionPane.YES_OPTION)
            {
                if(fc.excluir(Integer.parseInt(txtCodigo.getText())))
                {
                    m.InformationMessage("Funcionario Demitido com sucesso!", "Informação");
                    limpar();
                }
                else
                {
                    m.ErroMessage("Erro ao Demitir o Funcioanrio", "Erro");
                }
            }            
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        limpar();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnLocalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLocalizarActionPerformed
        ConsultaPadrao consFuncionario = new ConsultaPadrao(null, true);
        String[] vet = new String[2];
        vet[0] = "Nome";
        vet[1] = "CPF";
        consFuncionario.configuraOpcoes(vet, 2, 1, "Funcionario", false);
        consFuncionario.verificaconsulta(true);
        consFuncionario.setVisible(true);
        if (consFuncionario.getCodigo() != 0)
        {
            txtCodigo.setText(""+consFuncionario.getCodigo());
            consFuncionario.dispose();
            txtCodigoFocusLost(null);
        }
        else
        {
            consFuncionario.dispose();
            btnLocalizar.requestFocus();
        }
    }//GEN-LAST:event_btnLocalizarActionPerformed

    private void btnGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGravarActionPerformed
        switch(fc.validar(txtCodigo.getText(), txtCodCid.getText(), txtNome.getText(), txtUsuario.getText(), txtSenha.getText(), soma, txtCpf.getText(), txtRg.getText(), txtOrgemi.getText(), txtEndereco.getText(), txtNumero.getText(), txtComplemento.getText(), txtTelefone.getText(), txtCelular.getText(), txtCaminho.getText(), txtCep.getText(), txtSenha1.getText()))
        {
            case 1: JOptionPane.showMessageDialog(this, "Informe a Cidade","Alerta", JOptionPane.WARNING_MESSAGE); 
            btnLocCidade.requestFocus();
            break;
            case 2: JOptionPane.showMessageDialog(this, "Informe o Nome","Alerta", JOptionPane.WARNING_MESSAGE);
            txtNome.requestFocus(); break;
            case 3:
            JOptionPane.showMessageDialog(this, "Informe o Login","Alerta", JOptionPane.WARNING_MESSAGE);
            txtUsuario.requestFocus();
            break;
            case 4:
            JOptionPane.showMessageDialog(this, "Informe a Senha","Alerta", JOptionPane.WARNING_MESSAGE);
            txtSenha.requestFocus();
            break;
            case 5:
            JOptionPane.showMessageDialog(this, "A senha não pode ter mais que 15 caracteres","Alerta", JOptionPane.WARNING_MESSAGE);
            txtSenha.requestFocus();
            break;
            case 6:
            JOptionPane.showMessageDialog(this, "Informe o Nivel desse usuraio","Alerta", JOptionPane.WARNING_MESSAGE);
            cbCadastro.requestFocus();
            break;
            case 7:
            JOptionPane.showMessageDialog(this, "Informe o Orgão emissor","Alerta", JOptionPane.WARNING_MESSAGE);
            txtOrgemi.requestFocus();
            break;
            case 8:
            JOptionPane.showMessageDialog(this, "Orgão emissor não pode ter mais que 2 caracteres","Alerta", JOptionPane.WARNING_MESSAGE);
            txtOrgemi.requestFocus();
            break;
            case 9:
            JOptionPane.showMessageDialog(this, "Informe o endereço","Alerta", JOptionPane.WARNING_MESSAGE);
            txtEndereco.requestFocus();
            break;
            case 10:
            JOptionPane.showMessageDialog(this, "Inforem o Número","Alerta", JOptionPane.WARNING_MESSAGE);
            txtNumero.requestFocus();
            break;
            case 11:
            JOptionPane.showMessageDialog(this, "informe Número","Alerta", JOptionPane.WARNING_MESSAGE);
            txtNumero.requestFocus();
            txtNumero.setText("");
            break;
            case 12:
            JOptionPane.showMessageDialog(this, "Inforem pelomenos o celular ou telefone","Alerta", JOptionPane.WARNING_MESSAGE);
            txtCelular.requestFocus();
            break;
            case 13:
            JOptionPane.showMessageDialog(this, "Inforem o CEP","Alerta", JOptionPane.WARNING_MESSAGE);
            txtCep.requestFocus();
            break;
            case 14:
            JOptionPane.showMessageDialog(this, "CPF ja Cadastrado","Alerta", JOptionPane.WARNING_MESSAGE);
            txtCpf.requestFocus();
            break;
            case 15:
            JOptionPane.showMessageDialog(this, "A senha não são iguais","Alerta", JOptionPane.WARNING_MESSAGE);
            txtSenha.requestFocus();
            txtSenha1.setText("");
            break;
            case 16:
            JOptionPane.showMessageDialog(this, "Informe o RG!","Alerta", JOptionPane.WARNING_MESSAGE);
            txtRg.requestFocus();
            break;
            case 17:
            JOptionPane.showMessageDialog(this, "Informe o CPF!","Alerta", JOptionPane.WARNING_MESSAGE);
            txtCpf.requestFocus();
            break;
            case 18:
            JOptionPane.showMessageDialog(this, "Informe o Nivel desse usuario!","Alerta", JOptionPane.WARNING_MESSAGE);
            m.WarmingMessage("Soma Atual"+soma, "Erro");
            break;
            default:
            if(fc.gravar())
            {
                JOptionPane.showMessageDialog(this, "Gravado com sucesso!","Informação", JOptionPane.INFORMATION_MESSAGE);
                limpar();
                if(firstAccess)
                {
                    dispose();
                }   
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Erro ao Gravar","Erro", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnGravarActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void txtCodigoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCodigoFocusLost
        if (!txtCodigo.getText().equals("0"))
        {
            fc.localizar(Integer.parseInt(txtCodigo.getText()));
            if (fc.getFunc() != null)
            {
                if(fc.getFunc().getDtdemicao()!= null)
                {
                    if(JOptionPane.showConfirmDialog(null, "Este funcinario ele foi demitido. Deseja Contratar Novamente?", "Confirmação", JOptionPane.INFORMATION_MESSAGE) == JOptionPane.YES_OPTION)
                    {
                        fc.getFunc().setCodigo(0);
                        if(fc.gravar())
                        {
                            m.InformationMessage("Funcioanrio Contratado com Sucesso", "Informação");
                        }
                        else
                        {
                            m.ErroMessage("Erro ao Contratar", "Erro");
                        }
                    }
                    else
                    {
                        limpar();
                        btnNovo.requestFocus();
                    }
                }
                else
                {
                    
                    ImageIcon icon = new ImageIcon(fc.getFunc().getCaminho());
                   // lFoto.setIcon(new ImageIcon(icon.getScaledInstance(lFoto.getWidth(),lFoto.getHeight())));
                    lFoto.setIcon(new ImageIcon(icon.getImage().getScaledInstance(lFoto.getWidth(), lFoto.getHeight(), Image.SCALE_DEFAULT))); // Utilizado para recuperar imagem.
                    txtCodigo.setText(""+fc.getFunc().getCodigo()); 
                    txtCidade.setText(fc.getFunc().getCid().getNome()); 
                    txtUf.setText(fc.getFunc().getCid().getE().getSigla()); 
                    txtNome.setText(fc.getFunc().getNome()); 
                    txtUsuario.setText(fc.getFunc().getLogin()); 
                    txtSenha.setText(fc.getFunc().getSenha()); 
                    soma = fc.getFunc().getNivel(); 
                    txtCpf.setText(fc.getFunc().getCpf()); 
                    txtRg.setText(fc.getFunc().getRg()); 
                    txtOrgemi.setText(fc.getFunc().getOrgemi()); 
                    txtEndereco.setText(fc.getFunc().getEndereco()); 
                    txtNumero.setText(""+fc.getFunc().getNumero()); 
                    txtComplemento.setText(fc.getFunc().getComplemento()); 
                    txtTelefone.setText(fc.getFunc().getTelefone());
                    txtCelular.setText(fc.getFunc().getCelular()); 
                    txtCaminho.setText(fc.getFunc().getCaminho()); 
                    txtCep.setText(fc.getFunc().getCep());
                    txtCodCid.setText(""+fc.getFunc().getCid().getCodigo());
                    levelアクセス(soma); // Acesso de nivel

                    sc.HabilityComponents(jPanel1.getComponents(), false);
                    sc.Alter(jPanel2.getComponents());
                }
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Funcionario não Encontrado", "Informação", JOptionPane.INFORMATION_MESSAGE);
                limpar();
                btnNovo.requestFocus();
            }
        }
    }//GEN-LAST:event_txtCodigoFocusLost

    private void btnaddCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddCidadeActionPerformed
        CadastroCidade frm = new CadastroCidade(null, true);
        frm.setVisible(true);
    }//GEN-LAST:event_btnaddCidadeActionPerformed

    private void btnLocCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLocCidadeActionPerformed
        ConsultaPadrao consCidade = new ConsultaPadrao(null, true);
        String[] vet = new String[2];
        vet[0] = "Código";
        vet[1] = "Cidade";
        consCidade.configuraOpcoes(vet, 2, 1, "Cidade", false);
        consCidade.verificaconsulta(true);
        consCidade.setVisible(true);
        if (consCidade.getCodigo() != 0)
        {
            fc.localizarCidade(consCidade.getCodigo());
            consCidade.dispose();
            txtCodCid.setText(""+fc.getFunc().getCid().getCodigo());
            txtCidade.setText(fc.getFunc().getCid().getNome());
            txtUf.setText(fc.getFunc().getCid().getE().getSigla());
        }
        else
        {
            consCidade.dispose();
            btnLocCidade.requestFocus();
        }
    }//GEN-LAST:event_btnLocCidadeActionPerformed

    private void btnBuscaImgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscaImgActionPerformed
        String local = sc.CarregaLogo(lFoto);
        txtCaminho.setText(local);
    }//GEN-LAST:event_btnBuscaImgActionPerformed

    private void btnLimpaImgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpaImgActionPerformed
        lFoto.setIcon(null);
        txtCaminho.setText("");
    }//GEN-LAST:event_btnLimpaImgActionPerformed

    private void cbAdmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAdmActionPerformed
        if(cbAdm.isSelected())
        {
            cbCadastro.setSelected(false);
            cbConsulta.setSelected(false);
            cbMovimentacao.setSelected(false);
            cbRelatorio.setSelected(false);
            
            cbCadastro.setEnabled(false);
            cbConsulta.setEnabled(false);
            cbMovimentacao.setEnabled(false);
            cbRelatorio.setEnabled(false);
            
            soma = 64; 
        }
        else
        {
            cbCadastro.setEnabled(true);
            cbConsulta.setEnabled(true);
            cbMovimentacao.setEnabled(true);
            cbRelatorio.setEnabled(true);
            
            soma = 0;
        }
        jLNivelAtual.setText(""+soma);
    }//GEN-LAST:event_cbAdmActionPerformed

    private void cbCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCadastroActionPerformed
        if(cbCadastro.isSelected())
        {
            soma += 2; 
        }
        else
        {
            soma -= 2;
        }
        jLNivelAtual.setText(""+soma);
    }//GEN-LAST:event_cbCadastroActionPerformed

    private void cbConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbConsultaActionPerformed
        if(cbConsulta.isSelected())
        {
            soma += 4; 
        }
        else
        {
            soma -= 4;
        }
                jLNivelAtual.setText(""+soma);
    }//GEN-LAST:event_cbConsultaActionPerformed

    private void cbRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbRelatorioActionPerformed
        if(cbRelatorio.isSelected())
        {
            soma += 8; 
        }
        else
        {
            soma -= 8;
        }
                jLNivelAtual.setText(""+soma);
    }//GEN-LAST:event_cbRelatorioActionPerformed

    private void cbMovimentacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMovimentacaoActionPerformed
        if(cbMovimentacao.isSelected())
        {
            soma += 16; 
        }
        else
        {  
            soma -= 16;
        }
                jLNivelAtual.setText(""+soma);
    }//GEN-LAST:event_cbMovimentacaoActionPerformed

    private void btnLocCidadeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnLocCidadeKeyPressed
        if(btnLocCidade.isFocusable() && evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
            btnLocCidadeActionPerformed(null);
        }
    }//GEN-LAST:event_btnLocCidadeKeyPressed

    private void limpar()
    {
        txtCodigo.setText(""); 
        txtCidade.setText(""); 
        txtUf.setText(""); 
        txtNome.setText(""); 
        txtUsuario.setText(""); 
        txtSenha.setText(""); 
        soma = 0; 
        txtCpf.setText(""); 
        txtRg.setText(""); 
        txtOrgemi.setText(""); 
        txtEndereco.setText(""); 
        txtNumero.setText(""); 
        txtComplemento.setText(""); 
        txtTelefone.setText("");
        txtCelular.setText(""); 
        txtCaminho.setText(""); 
        txtCep.setText("");
        txtCodCid.setText("");
        
        cbCadastro.setSelected(false);
        cbConsulta.setSelected(false);
        cbMovimentacao.setSelected(false);
        cbRelatorio.setSelected(false);
        cbAdm.setSelected(false);
        
        soma = 0;
        sc.Initialize(jPanel2.getComponents());
        sc.HabilityComponents(jPanel1.getComponents(), false);
        sc.HabilityComponents(jPanel4.getComponents(), false);
        lFoto.setIcon(null);
        cbCadastro.setEnabled(false);
        cbConsulta.setEnabled(false);
        cbMovimentacao.setEnabled(false);
        cbRelatorio.setEnabled(false);
        cbAdm.setEnabled(false);
    }
    
    private void levelアクセス(int soma)
    {
        if(soma == 64)
        {
            cbAdm.setSelected(true);
        }
        else
        {
            if(soma >= 16)
            {
                cbMovimentacao.setSelected(true);
                soma -= 16;
            }
            if(soma >= 8)
            {
                cbRelatorio.setSelected(true);
                soma -= 8;
            }
            if(soma >= 4)
            {
                cbConsulta.setSelected(true);
                soma -= 4;
            }
            if(soma >= 2)
            {
                cbCadastro.setSelected(true);
                soma = 0;
            }
        }
    }

    private void habilityCB(boolean flag)
    {
        cbCadastro.setEnabled(flag);
        cbConsulta.setEnabled(flag);
        cbMovimentacao.setEnabled(flag);
        cbRelatorio.setEnabled(flag);
        cbAdm.setEnabled(flag);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnBuscaImg;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnGravar;
    private javax.swing.JButton btnLimpaImg;
    private javax.swing.JButton btnLocCidade;
    private javax.swing.JButton btnLocalizar;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnaddCidade;
    private javax.swing.JCheckBox cbAdm;
    private javax.swing.JCheckBox cbCadastro;
    private javax.swing.JCheckBox cbConsulta;
    private javax.swing.JCheckBox cbMovimentacao;
    private javax.swing.JCheckBox cbRelatorio;
    private javax.swing.JLabel jLNivelAtual;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lFoto;
    private javax.swing.JTextField txtCaminho;
    private javax.swing.JFormattedTextField txtCelular;
    private javax.swing.JFormattedTextField txtCep;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JTextField txtCodCid;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtComplemento;
    private javax.swing.JFormattedTextField txtCpf;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtOrgemi;
    private javax.swing.JFormattedTextField txtRg;
    private javax.swing.JPasswordField txtSenha;
    private javax.swing.JPasswordField txtSenha1;
    private javax.swing.JFormattedTextField txtTelefone;
    private javax.swing.JTextField txtUf;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
