package CamadaApresentacao;

import CamadaLogica.ReadOnlyTableModel;
import CamadaNegocio.Funcionario;
import Controller.LancarCompraController;
import java.awt.event.KeyEvent;
import java.time.Instant;
import java.util.Date;
import javax.swing.JOptionPane;
import util.SystemControl;
import util.mensagens;

/**
 * Moniter
 * @author 吉野　廉
 * @author 羽根川　翼
 * Produto
 * @author 香取 
 * @author 鹿島
 * @author 橋立
 * Folha
 * @author 海女
 * @author 御子
 * @author 稲荷
 * 
 * Tester 2019/07/23
 * @author 弐条
 * @author 七草
*/
public class MovLancarCompras extends javax.swing.JDialog {

    private final SystemControl sc = new SystemControl();
    private final mensagens m = new mensagens();
    private final LancarCompraController lcc = new LancarCompraController();
    private boolean flag;
    
    public MovLancarCompras(java.awt.Frame parent, boolean modal, Funcionario f) {
        super(parent, modal);
        initComponents();
        
        setLocationRelativeTo(null);
        
        btnNovo.setName("btnNovo");
        btnAlterar.setName("btnAlterar");
        btnCancelar.setName("btnCancelar");
        btnExcluir.setName("btnExcluir");
        btnGravar.setName("btnGravar");
        btnLocalizar.setName("btnLocalizar");
        btnSair.setName("btnSair");
        
//        btnAlterar.setVisible(false);
//        btnExcluir.setVisible(false);
//        btnLocalizar.setVisible(false);
        
        btnaddDF.setName("btnaddDF");
        btnExcluirF.setName("btnExcluirF");
        btnAltF.setName("btnAltF");
        
        btnaddDP.setName("btnaddDP");
        btnexcP.setName("btnexcP");
        btnaltP.setName("btnaltP");
        
        btnaddF.setName("btnaddF");
        btnlocF.setName("btnlocF");
        btnaddProd.setName("btnaddProd");
        btnLocProd.setName("btnLocProd");
        jTabbedPane1.setMnemonicAt(0, KeyEvent.VK_P);
        jTabbedPane1.setMnemonicAt(1, KeyEvent.VK_F);
        
        lcc.getForn().setCodigo(0);
        
        lcc.getC().setFunc(f);
        LancarCompraController.configuraModelItem(tbF);
        LancarCompraController.configuraModelItem(tbP);
        sc.HabilityComponents(jPanel1.getComponents(), false);
        sc.Initialize(jPanel2.getComponents());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbP = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        txtcodP = new javax.swing.JTextField();
        txtproduto = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btnLocProd = new javax.swing.JButton();
        btnaddProd = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtqtdP = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtvalortP = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        btnaddDP = new javax.swing.JButton();
        btnexcP = new javax.swing.JButton();
        btnaltP = new javax.swing.JButton();
        txtprecoP = new br.com.ikeda.beans.jTextFieldMonetario();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbF = new javax.swing.JTable();
        txtValorTF = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtCodigoF = new javax.swing.JTextField();
        txtFolha = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        btnaddF = new javax.swing.JButton();
        btnlocF = new javax.swing.JButton();
        txtQtdF = new javax.swing.JTextField();
        btnAltF = new javax.swing.JButton();
        btnExcluirF = new javax.swing.JButton();
        btnaddDF = new javax.swing.JButton();
        txtPrecoF = new br.com.ikeda.beans.jTextFieldMonetario();
        jLabel18 = new javax.swing.JLabel();
        txtvalorTotP = new javax.swing.JTextField();
        txtvalorTotF = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtvalorF = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtforn = new javax.swing.JTextField();
        btnaddForn = new javax.swing.JButton();
        btnLocForn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnNovo = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnGravar = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnLocalizar = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setText("Codigo:");

        txtCodigo.setEditable(false);
        txtCodigo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtCodigo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCodigoFocusLost(evt);
            }
        });

        tbP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tbP);

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setText("Codigo:");

        txtcodP.setEditable(false);
        txtcodP.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        txtproduto.setEditable(false);
        txtproduto.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setText("Produto:");

        btnLocProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Localizar 16.png"))); // NOI18N
        btnLocProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLocProdActionPerformed(evt);
            }
        });

        btnaddProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Novo 16.png"))); // NOI18N
        btnaddProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddProdActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setText("Quantidade:");

        txtqtdP.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtqtdP.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtqtdPFocusLost(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel9.setText("Preço Unitario:");

        txtvalortP.setEditable(false);
        txtvalortP.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel11.setText("Valor Total:");

        btnaddDP.setText("Adicionar Dados");
        btnaddDP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddDPActionPerformed(evt);
            }
        });

        btnexcP.setText("Excluir");
        btnexcP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexcPActionPerformed(evt);
            }
        });

        btnaltP.setText("Alterar");
        btnaltP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaltPActionPerformed(evt);
            }
        });

        txtprecoP.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtprecoPFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtcodP, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtproduto, javax.swing.GroupLayout.PREFERRED_SIZE, 543, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnaddProd))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtqtdP, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtprecoP, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtvalortP, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnaddDP)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnexcP)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnaltP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(btnLocProd)
                .addContainerGap())
            .addComponent(jScrollPane1)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtcodP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLocProd, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(txtproduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnaddProd, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtqtdP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txtprecoP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel11)
                                .addComponent(txtvalortP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnaltP, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnexcP, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnaddDP, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(200, 200, 200))))
        );

        jTabbedPane1.addTab("Produto", jPanel3);

        tbF.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tbF);

        txtValorTF.setEditable(false);
        txtValorTF.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel12.setText("Valor Total:");

        jLabel13.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel13.setText("Quantidade:");

        jLabel14.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel14.setText("Folha:");

        jLabel15.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel15.setText("Codigo:");

        txtCodigoF.setEditable(false);
        txtCodigoF.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        txtFolha.setEditable(false);
        txtFolha.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLabel16.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel16.setText("Preço Unitario:");

        btnaddF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Novo 16.png"))); // NOI18N
        btnaddF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddFActionPerformed(evt);
            }
        });

        btnlocF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Localizar 16.png"))); // NOI18N
        btnlocF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlocFActionPerformed(evt);
            }
        });

        txtQtdF.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtQtdF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtQtdFFocusLost(evt);
            }
        });

        btnAltF.setText("Alterar");
        btnAltF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAltFActionPerformed(evt);
            }
        });

        btnExcluirF.setText("Excluir");
        btnExcluirF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirFActionPerformed(evt);
            }
        });

        btnaddDF.setText("Adicionar Dados");
        btnaddDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddDFActionPerformed(evt);
            }
        });

        txtPrecoF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPrecoFFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCodigoF, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtFolha, javax.swing.GroupLayout.PREFERRED_SIZE, 543, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnaddF)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnlocF))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtQtdF, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(12, 12, 12)
                                        .addComponent(jLabel16)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtPrecoF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                                        .addGap(4, 4, 4)
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtValorTF, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnaddDF)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnExcluirF)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAltF)))
                        .addGap(0, 19, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtCodigoF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel14)
                        .addComponent(txtFolha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnaddF, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnlocF, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel16)
                    .addComponent(txtQtdF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPrecoF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(txtValorTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnAltF, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExcluirF, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnaddDF, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Folha", jPanel5);

        jLabel18.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel18.setText("Valor Total Produto:");

        txtvalorTotP.setEditable(false);
        txtvalorTotP.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        txtvalorTotF.setEditable(false);
        txtvalorTotF.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLabel19.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel19.setText("Valor Total Folha:");

        txtvalorF.setEditable(false);
        txtvalorF.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLabel25.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel25.setText("Valor Total Final:");

        jLabel10.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel10.setText("Fornecedor:");

        txtforn.setEditable(false);
        txtforn.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        btnaddForn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Novo 16.png"))); // NOI18N
        btnaddForn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddFornActionPerformed(evt);
            }
        });

        btnLocForn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Localizar 16.png"))); // NOI18N
        btnLocForn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLocFornActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtvalorTotP, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtvalorTotF, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtforn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnaddForn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLocForn)
                        .addGap(29, 29, 29))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtvalorF, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10)
                        .addComponent(txtforn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnLocForn, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnaddForn, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txtvalorTotP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(txtvalorTotF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(txtvalorF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Novo 16.png"))); // NOI18N
        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Alterar16.png"))); // NOI18N
        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Excluir16.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnGravar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Gravar16.png"))); // NOI18N
        btnGravar.setText("Gravar");
        btnGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGravarActionPerformed(evt);
            }
        });

        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Sair.png"))); // NOI18N
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Cancelar16.png.jpg"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnLocalizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Localizar 16.png"))); // NOI18N
        btnLocalizar.setText("Localizar");
        btnLocalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLocalizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLocalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGravar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAlterar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                    .addComponent(btnNovo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSair, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGravar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnExcluir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLocalizar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        sc.HabilityComponents(jPanel1.getComponents(), true);
        sc.Edity(jPanel2.getComponents());
        txtCodigo.setText("0");
        txtValorTF.setText("0"); 
        txtvalorTotF.setText("0"); 
        txtvalorF.setText("0");
        txtvalortP.setText("0");
        flag = true;
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
       dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        sc.limpar(jPanel1.getComponents());
        sc.HabilityComponents(jPanel1.getComponents(), false);
        sc.HabilityComponents(jPanel3.getComponents(), false);
        sc.HabilityComponents(jPanel5.getComponents(), false);
        sc.limparTabela(tbF);
        sc.limparTabela(tbP);
        sc.Initialize(jPanel2.getComponents());
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnaddProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddProdActionPerformed
       CadastroProduto frm = new CadastroProduto(null, true);
       frm.setTitle("Cadastro Produto");
       frm.setVisible(true);
    }//GEN-LAST:event_btnaddProdActionPerformed

    private void btnLocProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLocProdActionPerformed
        ConsultaPadrao consProduto = new ConsultaPadrao(null, true);
        String[] vet = new String[1];
        vet[0] = "Nome";
        consProduto.configuraOpcoes(vet, 1, 0, "AProduto", false);
        consProduto.verificaconsulta(true);
        consProduto.setVisible(true);
        if (consProduto.getCodigo() != 0)
        {
            lcc.buscProduto(consProduto.getCodigo());
            txtcodP.setText(""+lcc.getP().getCodigo());
            txtproduto.setText(""+lcc.getP().getNome());
            txtqtdP.setText("0");
            txtprecoP.setText("1");
            txtvalortP.setText("0");
            consProduto.dispose();
        }
        else
        {
            consProduto.dispose();
            btnLocProd.requestFocus();
        }
    }//GEN-LAST:event_btnLocProdActionPerformed

    private void btnaddFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddFActionPerformed
       CadastroFolha frm = new CadastroFolha(null, true);
       frm.setTitle("Cadastro Folha");
       frm.setVisible(true);
    }//GEN-LAST:event_btnaddFActionPerformed

    private void btnlocFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlocFActionPerformed
        ConsultaPadrao consFolha = new ConsultaPadrao(null, true);
        String[] vet = new String[2];
        vet[0] = "Tamanho";
        vet[1] = "Descrição";
        consFolha.configuraOpcoes(vet, 2, 0, "AFolha", false);
        consFolha.verificaconsulta(true);
        consFolha.setVisible(true);
        if (consFolha.getCodigo() != 0)
        {
            lcc.buscaFolha(consFolha.getCodigo());
            txtCodigoF.setText(""+lcc.getF().getCodigo());
            txtFolha.setText(lcc.getF().getTamanho()+"\\"+lcc.getF().getDescricao());
            txtQtdF.setText("0");
            txtPrecoF.setText("1");
            txtValorTF.setText("0");
            consFolha.dispose();
            
        }
        else
        {
            consFolha.dispose();
            btnLocalizar.requestFocus();
        }
    }//GEN-LAST:event_btnlocFActionPerformed

    private void btnaddFornActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddFornActionPerformed
       CadastroFornecedor frm = new CadastroFornecedor(null, true);
       frm.setTitle("Cadastro Fornecedor");
       frm.setVisible(true);
    }//GEN-LAST:event_btnaddFornActionPerformed

    private void btnLocFornActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLocFornActionPerformed
        ConsultaPadrao consFornecedor = new ConsultaPadrao(null, true);
        String[] vet = new String[1];
        vet[0] = "Nome";
        consFornecedor.configuraOpcoes(vet, 1, 0, "Fornecedor", false);
        consFornecedor.verificaconsulta(true);
        consFornecedor.setVisible(true);
        if (consFornecedor.getCodigo() != 0)
        {
            lcc.buscFornecedor(consFornecedor.getCodigo());
            txtforn.setText(lcc.getForn().getNome()); 
            consFornecedor.dispose();
        }
        else
        {
            consFornecedor.dispose();
            btnLocalizar.requestFocus();
        }
    }//GEN-LAST:event_btnLocFornActionPerformed

    private void btnaddDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddDFActionPerformed
       switch(lcc.validar(txtCodigoF.getText(), txtFolha.getText(), txtQtdF.getText(), txtPrecoF.getText(), tbF, flag, txtCodigo.getText(), 2))
       {
           case 3: m.InformationMessage("Informe a Folha!", "Atenção"); btnLocProd.requestFocus(); break;
           case 4: m.InformationMessage("O item não pode ser inserido!", "Atenção"); break;
           case 6: m.WarmingMessage("Ao alterar essa quantidade o estoque ficara negativa!\n Por esse motivo, não pode ser alterado!", "Atenção"); break;
           default:
//                if(flag)
//                {
                    lcc.CalculaTotalI(txtvalorTotF, tbF);
                    lcc.CalculaTotal(txtvalorTotP, txtvalorTotF, txtvalorF);
                    txtCodigoF.setText("");
                    txtFolha.setText("");
                    txtQtdF.setText("0");
                    txtPrecoF.setText("1");
                    txtValorTF.setText("0");
//                }
//                else
//                {
//                   ReadOnlyTableModel model = (ReadOnlyTableModel) tbP.getModel();
//                   if(lcc.buscarTabelaProduto(Integer.parseInt(txtCodigo.getText()), Integer.parseInt(txtCodigoF.getText())) && lcc.verificarEstoqueProduto(Integer.parseInt(txtCodigoF.getText()), Integer.parseInt(txtQtdF.getText())))
//                   {
//                        lcc.CalculaTotalI(txtvalorTotP, tbP);
//                        lcc.CalculaTotal(txtvalorTotP, txtvalorTotF, txtvalorF);
//                        txtCodigoF.setText("");
//                        txtFolha.setText("");
//                        txtQtdF.setText("0");
//                        txtPrecoF.setText("1");
//                        txtValorTF.setText("0");
//                        btnlocF.setEnabled(true);      
//                   }
//                   else
//                   {
//                       m.WarmingMessage("Ao alterar essa quantidade o estoque ficara negativa!\n Por esse motivo, não pode ser alterado!", "Atenção");
//                   }
//                }
       }
    }//GEN-LAST:event_btnaddDFActionPerformed

    private void btnaddDPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddDPActionPerformed
       switch(lcc.validar(txtcodP.getText(), txtproduto.getText(), txtqtdP.getText(), txtprecoP.getText(), tbP, flag, txtCodigo.getText(), 1))
       {
           case 3: m.InformationMessage("Informe o Produto!", "Atenção"); btnlocF.requestFocus(); break;
           case 4: m.InformationMessage("O item não pode ser inserido!", "Atenção"); break;
           case 5: m.WarmingMessage("Ao alterar essa quantidade o estoque ficara negativa!\n Por esse motivo, não pode ser alterado!", "Atenção"); break;
           default: 
//               if(flag)
//               {
                    lcc.CalculaTotalI(txtvalorTotP, tbP);
                    lcc.CalculaTotal(txtvalorTotP, txtvalorTotF, txtvalorF);
                    txtcodP.setText("");
                    txtproduto.setText("");
                    txtqtdP.setText("0");
                    txtprecoP.setText("1");
                    txtvalortP.setText("0");
                    btnLocProd.setEnabled(true);
//               }
//               else
//               {
//                   ReadOnlyTableModel model = (ReadOnlyTableModel) tbP.getModel();
//                   if(lcc.buscarTabelaProduto(Integer.parseInt(txtCodigo.getText()), Integer.parseInt(txtcodP.getText())) && lcc.verificarEstoqueProduto(Integer.parseInt(txtcodP.getText()), Integer.parseInt(txtqtdP.getText())))
//                   {
//                        lcc.CalculaTotalI(txtvalorTotP, tbP);
//                        lcc.CalculaTotal(txtvalorTotP, txtvalorTotF, txtvalorF);
//                        txtcodP.setText("");
//                        txtproduto.setText("");
//                        txtqtdP.setText("0");
//                        txtprecoP.setText("1");
//                        txtvalortP.setText("0");
//                        btnLocProd.setEnabled(true);      
//                   }
//                   else
//                   {
//                       m.WarmingMessage("Ao alterar essa quantidade o estoque ficara negativa!\n Por esse motivo, não pode ser alterado!", "Atenção");
//                   }
//               }
       }
    }//GEN-LAST:event_btnaddDPActionPerformed

    private void txtqtdPFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtqtdPFocusLost
       switch(lcc.Calcula(txtqtdP, txtprecoP, txtvalortP))
       {
           case 1: m.InformationMessage("Informe a quantidade! A Quantidade precisa ser mairo que 0!", "Atenção"); txtqtdP.requestFocus(); break;
           case 2: m.InformationMessage("Informe o valor! O Valor precisa ser mairo que 0!", "Atenção"); txtprecoP.requestFocus(); break;
       }
    }//GEN-LAST:event_txtqtdPFocusLost

    private void txtQtdFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtQtdFFocusLost
       switch(lcc.Calcula(txtQtdF, txtPrecoF, txtValorTF))
       {
           case 1: m.InformationMessage("Informe a quantidade! A Quantidade precisa ser mairo que 0!", "Atenção"); txtQtdF.requestFocus(); break;
           case 2: m.InformationMessage("Informe o valor! O Valor precisa ser mairo que 0!", "Atenção"); txtPrecoF.requestFocus(); break;
       }  
    }//GEN-LAST:event_txtQtdFFocusLost

    private void btnAltFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAltFActionPerformed
        if(tbF.getSelectedRow() >= 0)
        {
            txtCodigoF.setText(""+tbF.getValueAt(tbF.getSelectedRow(), 0));
            txtFolha.setText(""+tbF.getValueAt(tbF.getSelectedRow(), 1));
            txtQtdF.setText(""+tbF.getValueAt(tbF.getSelectedRow(), 2));
            txtPrecoF.setText(""+sc.verificaValor(String.valueOf(tbF.getValueAt(tbF.getSelectedRow(), 3))));
            txtValorTF.setText(""+tbF.getValueAt(tbF.getSelectedRow(), 4));
            ReadOnlyTableModel model = (ReadOnlyTableModel) tbF.getModel();
            model.removeRow(tbF.getSelectedRow());
        }
        else
        {
            m.InformationMessage("Selecione uma linha!", "Atenção"); 
            tbF.requestFocus();
        }
    }//GEN-LAST:event_btnAltFActionPerformed

    private void btnaltPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaltPActionPerformed
        if(tbP.getSelectedRow() >= 0)
        {
            if(!flag)
            {
                btnLocProd.setEnabled(false);
            }
            txtcodP.setText(""+tbP.getValueAt(tbP.getSelectedRow(), 0));
            txtproduto.setText(""+tbP.getValueAt(tbP.getSelectedRow(), 1));
            txtqtdP.setText(""+tbP.getValueAt(tbP.getSelectedRow(), 2));
            txtprecoP.setText(""+sc.verificaValor(String.valueOf(tbP.getValueAt(tbP.getSelectedRow(), 3))));
            txtvalortP.setText(""+tbP.getValueAt(tbP.getSelectedRow(), 4));
            ReadOnlyTableModel model = (ReadOnlyTableModel) tbP.getModel();
            model.removeRow(tbP.getSelectedRow());
        }
        else
        {
            m.InformationMessage("Selecione uma linha!", "Atenção"); 
            tbP.requestFocus();
        }
    }//GEN-LAST:event_btnaltPActionPerformed

    private void btnexcPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexcPActionPerformed
        if(m.Pergunta("Deseja realmente Excluir esta Linha?", "Atenção") == JOptionPane.YES_OPTION)
        {    
            if(flag)
            {
                    lcc.ExcluirLinha(tbP, txtvalorTotP, txtValorTF);
                    lcc.CalculaTotal(txtvalorTotP, txtvalorTotF, txtvalorF);
                    m.InformationMessage("Excluido com Sucesso!", "Atenção");

            }
            else
            {
                ReadOnlyTableModel model = (ReadOnlyTableModel) tbP.getModel();
                if(lcc.verificarEstoqueProduto(Integer.parseInt(txtcodP.getText()), Integer.parseInt(txtqtdP.getText())))
                {
                    m.InformationMessage("Excluido com Sucesso!", "Atenção");
                }
                else
                {
                    m.WarmingMessage("Não pode ser excluido pelo fato do estque deste produto ficar negativo!", "Atenção");
                }
                //存在するのか確認。 OK
                //存在すれば、現在のストック数と新しく入力したストック数が　
                //現在のストック-予約済みのストック数-新しく入力したストック数　＜０の場合、エラーを戻す。 OK
            }
        }
    }//GEN-LAST:event_btnexcPActionPerformed

    private void btnExcluirFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirFActionPerformed
        if(m.Pergunta("Deseja realmente Excluir esta Linha?", "Atenção") == JOptionPane.YES_OPTION)
        {
            if(flag)
            {
                lcc.ExcluirLinha(tbF, txtvalorTotF, txtValorTF);
                lcc.CalculaTotal(txtvalorTotP, txtvalorTotF, txtvalorF);
                m.InformationMessage("Excluido com Sucesso!", "Atenção");
            }
            else
            {
                ReadOnlyTableModel model = (ReadOnlyTableModel) tbP.getModel();
                if(lcc.verificarEstoqueProduto(Integer.parseInt(txtcodP.getText()), Integer.parseInt(txtqtdP.getText())))
                {
                    lcc.ExcluirLinha(tbF, txtvalorTotF, txtValorTF);
                    lcc.CalculaTotal(txtvalorTotP, txtvalorTotF, txtvalorF);
                    m.InformationMessage("Excluido com Sucesso!", "Atenção");
                }
                else
                {
                    m.WarmingMessage("Não pode ser excluido pelo fato do estque desta Folha ficar negativa!", "Atenção");
                }
            }
        }
    }//GEN-LAST:event_btnExcluirFActionPerformed

    private void btnGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGravarActionPerformed
        if(lcc.gravar(txtCodigo.getText(), txtvalorF.getText(), tbP, tbF))
        {
            m.InformationMessage("Gravado com sucesso!", "Atenção");
            lancarConta();
            sc.limpar(jPanel1.getComponents());
            sc.limparTabela(tbF);
            sc.limparTabela(tbP);
            sc.Initialize(jPanel2.getComponents());
            sc.HabilityComponents(jPanel1.getComponents(), false);
            sc.HabilityComponents(jPanel3.getComponents(), false);
            sc.HabilityComponents(jPanel5.getComponents(), false);
        }
        else
        {
            m.ErroMessage("Erro ao Gravar", "ERRO");
        }
    }//GEN-LAST:event_btnGravarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        if(m.Pergunta("Deseja realmente Excluir esta Compra? Não podera ser recuperado mais!", "Atenção") == JOptionPane.YES_OPTION)
        {
            if(m.Pergunta("Certesa?", "Atenção") == JOptionPane.YES_OPTION)
            {
                switch(lcc.excluir())
                {
                    case 1:
                        m.WarmingMessage("Ja existe uma ou mais parsela paga! Não pode ser excluido!", "Atenção");
                        break;
                    case 2:
                        m.WarmingMessage("Não pode ser excluido pelo fato do estoque ficar negativo!", "Atenção");
                        break;
                    case 3:
                        m.ErroMessage("Erro ao Excluir!", "ERRO");
                        break;
                    default:
                        m.InformationMessage("Excluido com Sucesso!", "Atenção");
                        btnCancelarActionPerformed(null);
                }
            }
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void txtCodigoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCodigoFocusLost
        if(!txtCodigo.getText().equals("0") && !txtCodigo.getText().equals(""))
        {
            lcc.buscaCompra(Integer.parseInt(txtCodigo.getText()));
            txtforn.setText(lcc.getC().getF().getNome());
            txtvalorF.setText(""+lcc.getC().getValort());
            lcc.addItens(tbF, tbP, txtvalorTotF, txtvalorTotP);
            sc.Alter(jPanel2.getComponents());
        }
    }//GEN-LAST:event_txtCodigoFocusLost

    private void btnLocalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLocalizarActionPerformed
        ConsultaMov consCompra = new ConsultaMov(null, true);
        String[] vet = new String[3];
        vet[0] = "Tudo";
        vet[1] = "Data";
        vet[2] = "Periodo";
        consCompra.configuraOpcoes(vet, 3, 0, "CCompra", false);
        consCompra.verificaconsulta(true);
        consCompra.setVisible(true);
        if (consCompra.getCodigo() != 0)
        {
            txtCodigo.setText(String.valueOf(consCompra.getCodigo()));
            if(!lcc.verificarParcelars(consCompra.getCodigo()))
            {
                m.InformationMessage("Esta compra não pode ser alterada pelo fato de já existir\n uma ou mais parcelas paga!", "Atenção");
                consCompra.dispose();
                btnLocalizar.requestFocus();    
            }
            else
            {
                sc.limparTabela(tbF);
                sc.limparTabela(tbP);
                consCompra.dispose();
                txtCodigoFocusLost(null);
                sc.Alter(jPanel2.getComponents());
            }
        }
        else
        {
            consCompra.dispose();
            btnLocalizar.requestFocus();
        }
    }//GEN-LAST:event_btnLocalizarActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated

    }//GEN-LAST:event_formWindowActivated

    private void txtprecoPFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtprecoPFocusLost
       switch(lcc.Calcula(txtqtdP, txtprecoP, txtvalortP))
       {
           case 1: m.InformationMessage("Informe a quantidade! A Quantidade precisa ser mairo que 0!", "Atenção"); txtqtdP.requestFocus(); break;
           case 2: m.InformationMessage("Informe o valor! O Valor precisa ser mairo que 0!", "Atenção"); txtprecoP.requestFocus(); break;
       }
    }//GEN-LAST:event_txtprecoPFocusLost

    private void txtPrecoFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPrecoFFocusLost
        switch(lcc.Calcula(txtQtdF, txtPrecoF, txtValorTF))
       {
           case 1: m.InformationMessage("Informe a quantidade! A Quantidade precisa ser mairo que 0!", "Atenção"); txtQtdF.requestFocus(); break;
           case 2: m.InformationMessage("Informe o valor! O Valor precisa ser mairo que 0!", "Atenção"); txtPrecoF.requestFocus(); break;
       }  
    }//GEN-LAST:event_txtPrecoFFocusLost

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        flag = false;
        sc.HabilityComponents(jPanel1.getComponents(), true);
        sc.HabilityComponents(jPanel3.getComponents(), true);
        sc.HabilityComponents(jPanel5.getComponents(), true);
        sc.Edity(jPanel2.getComponents());
    }//GEN-LAST:event_btnAlterarActionPerformed

    
    private void lancarConta()
    {
        String lista[] = {"Vista","Parcelado","Prazo"};
        Object valor;
        do{
            valor = JOptionPane.showInputDialog(this, "Atenção", 
                    "Informe a modeo de pagamento:", JOptionPane.INFORMATION_MESSAGE,
                    null, lista, lista[0]);
        }while(valor == null);
        if(valor.equals("Vista"))
        {//Vista
            lcc.lancarContaPagar(Date.from(Instant.now()));
            m.InformationMessage("Conta a receber Lançado com Sucesso!", "Informação");
        }
        else
        {
            Date data;
            DateMessage messegeDate = new DateMessage(null, true, "Atenção", "Informe a Data de Vencimento:");
            data = messegeDate.getData();
            if(valor.equals("Parcelado"))
            {//Parcelado
                GerenciarParcela formGP = new GerenciarParcela(null, true, null, lcc.getC(), null);
                formGP.setVisible(true);
                m.InformationMessage("Parcelas Lançados com Sucesso!", "Informação");
            }
            else
            {//Prazo
                lcc.lancarContaPagar(data);
                m.InformationMessage("Conta a receber Lançado com Sucesso!", "Informação");
            }
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAltF;
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnExcluirF;
    private javax.swing.JButton btnGravar;
    private javax.swing.JButton btnLocForn;
    private javax.swing.JButton btnLocProd;
    private javax.swing.JButton btnLocalizar;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnaddDF;
    private javax.swing.JButton btnaddDP;
    private javax.swing.JButton btnaddF;
    private javax.swing.JButton btnaddForn;
    private javax.swing.JButton btnaddProd;
    private javax.swing.JButton btnaltP;
    private javax.swing.JButton btnexcP;
    private javax.swing.JButton btnlocF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tbF;
    private javax.swing.JTable tbP;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtCodigoF;
    private javax.swing.JTextField txtFolha;
    private br.com.ikeda.beans.jTextFieldMonetario txtPrecoF;
    private javax.swing.JTextField txtQtdF;
    private javax.swing.JTextField txtValorTF;
    private javax.swing.JTextField txtcodP;
    private javax.swing.JTextField txtforn;
    private br.com.ikeda.beans.jTextFieldMonetario txtprecoP;
    private javax.swing.JTextField txtproduto;
    private javax.swing.JTextField txtqtdP;
    private javax.swing.JTextField txtvalorF;
    private javax.swing.JTextField txtvalorTotF;
    private javax.swing.JTextField txtvalorTotP;
    private javax.swing.JTextField txtvalortP;
    // End of variables declaration//GEN-END:variables
}
