package CamadaApresentacao;

import CamadaLogica.ReadOnlyTableModel;
import CamadaNegocio.Funcionario;
import Controller.OrcamentoController;
import java.awt.Font;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import util.SystemControl;
import util.Validacao;
import util.mensagens;

/**
 * @author 吉野　廉
 * @author 羽根川　翼
 * @author モニカ
 * @author 阿武隈
 * @author 長門
 * @author 大和
 * @author 阿賀野
 * @author 矢矧
 * @author 長良
 * @author 天野
 * @author 紅葉
 * 
 * Tester 1 2019年07月24～25日
 * @author 吹雪
 * @author 白雪
 * @author 東雲
 * @author 曙
 * @author 漣
 * 
 * Tester 2 2019年08月03日
 * @author 織田
 * @author 真田
 * @author 服部
 * @author 島雪
 * @author 山雪
 */
public class MovOrcamneto extends javax.swing.JDialog {


    private final util.SystemControl sc = new SystemControl();
    private final mensagens m = new mensagens();
    private final OrcamentoController oc = new OrcamentoController();
    private final Validacao v = new Validacao(); 
    private boolean flag;
    private int linha;
    
    public MovOrcamneto(java.awt.Frame parent, boolean modal, Funcionario F) throws SQLException {
        super(parent, modal);
        initComponents();
        
        setLocationRelativeTo(null);
        
        btnNovo.setName("btnNovo");
        btnAlterar.setName("btnAlterar");
        btnCancelar.setName("btnCancelar");
        btnExcluir.setName("btnExcluir");
        btnGravar.setName("btnGravar");
        btnLocalizar.setName("btnLocalizar");
        btnSair.setName("btnSair");
        
        btnAddServico.setName("btnAddServico");
        btnaddCliente.setName("btnaddCliente");
        btnaddDetalhe.setName("btnaddDetalhe");
        btnaddServico.setName("btnaddServico");
        btnlocCliente.setName("btnlocCliente");
        btnlocServico.setName("btnlocServico");
        btnPDF.setName("btnPDF"); 
        
        oc.getO().setF(F);
        
        txtCodigo.setEditable(false);
        LCodigoServi.setVisible(false);
        txtDescServi.setVisible(false);
        OrcamentoController.configuraModelServico(jTable1);
        OrcamentoController.configuraModelDetalhe(jTable2);
        sc.HabilityComponents(jPanel1.getComponents(), false);
        sc.Initialize(jPanel2.getComponents());
        //サービスの詳細を追加して下さい ===>>> 追加済み.
        oc.carregarDetalhes(cbDescricao);
        oc.carregarFormaPagamento(cbForma);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btnNovo = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnGravar = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnPDF = new javax.swing.JButton();
        btnLocalizar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtCliente = new javax.swing.JTextField();
        btnaddCliente = new javax.swing.JButton();
        btnlocCliente = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        txtServico = new javax.swing.JTextField();
        btnaddServico = new javax.swing.JButton();
        btnlocServico = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtValor_total = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDescricao = new javax.swing.JTextArea();
        btnAddServico = new javax.swing.JButton();
        btnExcluirServi = new javax.swing.JButton();
        btnAlterarServico = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        LCodigoServi = new javax.swing.JLabel();
        txtCustoP = new br.com.ikeda.beans.jTextFieldMonetario();
        txtCustoI = new br.com.ikeda.beans.jTextFieldMonetario();
        txtCustoMdO = new br.com.ikeda.beans.jTextFieldMonetario();
        txtCustoChap = new br.com.ikeda.beans.jTextFieldMonetario();
        txtCustoArt = new br.com.ikeda.beans.jTextFieldMonetario();
        txtCustoAcab = new br.com.ikeda.beans.jTextFieldMonetario();
        txtDesconto = new br.com.ikeda.beans.jTextFieldMonetario();
        spQtd = new javax.swing.JSpinner();
        txtValor = new br.com.ikeda.beans.jTextFieldMonetario();
        jLabel13 = new javax.swing.JLabel();
        txtValorT = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        dcDataPedido = new br.com.marciorl.beans.DateChooser();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        txtDescServi = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        cbDescricao = new javax.swing.JComboBox<>();
        labelTexto1 = new javax.swing.JLabel();
        txtNumeracaoI = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtNumeracaoF = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        labelTexto2 = new javax.swing.JLabel();
        txtVia = new javax.swing.JTextField();
        txtOutros = new javax.swing.JTextField();
        labelTexto3 = new javax.swing.JLabel();
        btnaddDetalhe = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        cbForma = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        dcDataVencimento = new br.com.marciorl.beans.DateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnNovo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Novo 16.png"))); // NOI18N
        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnAlterar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Alterar16.png"))); // NOI18N
        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnExcluir.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Excluir16.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnGravar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnGravar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Gravar16.png"))); // NOI18N
        btnGravar.setText("Gravar");
        btnGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGravarActionPerformed(evt);
            }
        });

        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Sair.png"))); // NOI18N
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Cancelar16.png.jpg"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnPDF.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnPDF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/pdf32.png"))); // NOI18N
        btnPDF.setText("Gerar PDF");

        btnLocalizar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnLocalizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Localizar 16.png"))); // NOI18N
        btnLocalizar.setText("Localizar");
        btnLocalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLocalizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLocalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnPDF)
                .addGap(62, 62, 62)
                .addComponent(btnGravar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(213, 213, 213)
                .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAlterar, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                    .addComponent(btnNovo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPDF, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGravar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLocalizar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnExcluir, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setText("Numero:");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("Nome do Cliente:");

        txtCodigo.setEditable(false);
        txtCodigo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtCodigo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCodigoFocusLost(evt);
            }
        });

        txtCliente.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        btnaddCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Novo 16.png"))); // NOI18N
        btnaddCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddClienteActionPerformed(evt);
            }
        });

        btnlocCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Localizar 16.png"))); // NOI18N
        btnlocCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlocClienteActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Pedido", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 12))); // NOI18N

        jTable1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("Serviço:");

        txtServico.setEditable(false);
        txtServico.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        btnaddServico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Novo 16.png"))); // NOI18N
        btnaddServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddServicoActionPerformed(evt);
            }
        });

        btnlocServico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Localizar 16.png"))); // NOI18N
        btnlocServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlocServicoActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setText("Valor/unitario:");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setText("Quantidade:");

        txtValor_total.setEditable(false);
        txtValor_total.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel8.setText("Valor Total:");

        jLabel9.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel9.setText("Descrição:");

        txtDescricao.setColumns(20);
        txtDescricao.setRows(5);
        jScrollPane2.setViewportView(txtDescricao);

        btnAddServico.setText("Adicionar");
        btnAddServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddServicoActionPerformed(evt);
            }
        });

        btnExcluirServi.setText("Excluir");
        btnExcluirServi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirServiActionPerformed(evt);
            }
        });

        btnAlterarServico.setText("Alterar");
        btnAlterarServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarServicoActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel17.setText("Custo Papel:");

        jLabel18.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel18.setText("Custo Arte:");

        jLabel19.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel19.setText("Custo Impressão:");

        jLabel20.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel20.setText("Custo Acabamento:");

        jLabel21.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel21.setText("Custo Chapa:");

        jLabel22.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel22.setText("Custo Mão de Obra:");

        jLabel23.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel23.setText("Desconto:");

        LCodigoServi.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        txtCustoP.setText(".0");
        txtCustoP.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCustoPFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCustoPFocusLost(evt);
            }
        });
        txtCustoP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCustoPActionPerformed(evt);
            }
        });

        txtCustoI.setText(".0");
        txtCustoI.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCustoIFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCustoIFocusLost(evt);
            }
        });
        txtCustoI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCustoIActionPerformed(evt);
            }
        });

        txtCustoMdO.setText(".0");
        txtCustoMdO.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCustoMdOFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCustoMdOFocusLost(evt);
            }
        });
        txtCustoMdO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCustoMdOActionPerformed(evt);
            }
        });

        txtCustoChap.setText(".0");
        txtCustoChap.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCustoChapFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCustoChapFocusLost(evt);
            }
        });
        txtCustoChap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCustoChapActionPerformed(evt);
            }
        });

        txtCustoArt.setText(".0");
        txtCustoArt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCustoArtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCustoArtFocusLost(evt);
            }
        });
        txtCustoArt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCustoArtActionPerformed(evt);
            }
        });

        txtCustoAcab.setText(".0");
        txtCustoAcab.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCustoAcabFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCustoAcabFocusLost(evt);
            }
        });
        txtCustoAcab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCustoAcabActionPerformed(evt);
            }
        });

        txtDesconto.setText(".0");
        txtDesconto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtDescontoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDescontoFocusLost(evt);
            }
        });
        txtDesconto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescontoActionPerformed(evt);
            }
        });

        spQtd.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                spQtdFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                spQtdFocusLost(evt);
            }
        });

        txtValor.setText(".0");
        txtValor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtValorFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtValorFocusLost(evt);
            }
        });
        txtValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(spQtd, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel17)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtCustoP, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel19)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtCustoI, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtServico, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnaddServico, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10)
                                        .addComponent(btnlocServico, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel20)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtCustoAcab, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(jLabel18)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtCustoArt, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel21)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtCustoChap, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel22)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtCustoMdO, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGap(434, 434, 434)
                                                .addComponent(LCodigoServi))))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel23)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtValor_total, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 571, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnExcluirServi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnAlterarServico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnAddServico, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 812, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtServico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4))
                    .addComponent(btnlocServico, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnaddServico, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel17)
                    .addComponent(jLabel19)
                    .addComponent(txtCustoP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCustoI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spQtd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jLabel18)
                    .addComponent(jLabel21)
                    .addComponent(jLabel22)
                    .addComponent(txtCustoMdO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCustoChap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCustoArt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCustoAcab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(txtValor_total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel23)
                        .addComponent(txtDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(LCodigoServi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnAddServico)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExcluirServi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAlterarServico)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel13.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel13.setText("Valor total final:");

        txtValorT.setEditable(false);
        txtValorT.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLabel14.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        jLabel14.setText("Data do pedido:");

        dcDataPedido.setEditable(false);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Descrição", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 11))); // NOI18N

        jTable2.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable2);

        txtDescServi.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel10.setText("Descricao Serviço:");

        cbDescricao.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cbDescricaoFocusLost(evt);
            }
        });
        cbDescricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbDescricaoActionPerformed(evt);
            }
        });

        labelTexto1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelTexto1.setText("Numeração de:");

        txtNumeracaoI.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel12.setText("a");

        txtNumeracaoF.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jButton4.setText("Adicionar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Excluir");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        labelTexto2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelTexto2.setText("Vias:");

        txtVia.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        txtOutros.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        labelTexto3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelTexto3.setText("Outros:");

        btnaddDetalhe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Novo 16.png"))); // NOI18N
        btnaddDetalhe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddDetalheActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbDescricao, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnaddDetalhe, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jButton4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addComponent(labelTexto3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtOutros, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                            .addComponent(labelTexto2)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtVia, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                            .addComponent(labelTexto1)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtNumeracaoI, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                            .addComponent(jLabel12)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtNumeracaoF, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(txtDescServi, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(cbDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnaddDetalhe, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTexto1)
                    .addComponent(txtNumeracaoI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(txtNumeracaoF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTexto2)
                    .addComponent(txtVia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDescServi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTexto3)
                    .addComponent(txtOutros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Forma de Pagamento", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 12))); // NOI18N

        cbForma.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbForma, 0, 543, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(cbForma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel16.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel16.setText("Vencimento:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnaddCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnlocCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dcDataPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtValorT, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dcDataVencimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnlocCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnaddCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(dcDataPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel14)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(dcDataVencimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel16))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel13)
                        .addComponent(txtValorT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnaddClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddClienteActionPerformed
       CadastroCliente frm = new CadastroCliente(null, true);
       frm.setTitle("Cadastro Cliente");
       frm.setVisible(true);
    }//GEN-LAST:event_btnaddClienteActionPerformed

    private void btnlocClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlocClienteActionPerformed
        ConsultaPadrao consCliente = new ConsultaPadrao(null, true);
        String[] vet = new String[3];
        vet[0] = "Nome";
        vet[1] = "CPF";
        vet[2] = "CNPJ";
        consCliente.configuraOpcoes(vet, 3, 0, "Cliente", false);
        consCliente.verificaconsulta(true);
        consCliente.setVisible(true);
        if (consCliente.getCodigo() != 0)
        {
            oc.buscaClietne(consCliente.getCodigo());
            txtCliente.setText(""+oc.getO().getCli().getNome());
            consCliente.dispose();
        }
        else
        {
            consCliente.dispose();
        }
    }//GEN-LAST:event_btnlocClienteActionPerformed

    private void btnaddServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddServicoActionPerformed
       CadastroServico frm = new CadastroServico(null, true);
       frm.setTitle("Cadastro Serviço");
       frm.setVisible(true);
    }//GEN-LAST:event_btnaddServicoActionPerformed

    private void btnlocServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlocServicoActionPerformed
        ConsultaPadrao consServico = new ConsultaPadrao(null, true);
        String[] vet = new String[1];
        vet[0] = "Nome";
        consServico.configuraOpcoes(vet, 1, 0, "AServico", false);
        consServico.verificaconsulta(true);
        consServico.setVisible(true);
        if (consServico.getCodigo() != 0)
        {
            txtServico.setText(oc.exibirServico(consServico.getCodigo()));
            consServico.dispose();
        }
        else
        {
            consServico.dispose();
        }
    }//GEN-LAST:event_btnlocServicoActionPerformed

    private void btnaddDetalheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddDetalheActionPerformed
       CadastroDetalheServico frm = new CadastroDetalheServico(null, true);
       frm.setTitle("Cadastro Detalhe Serviço");
       frm.setVisible(true);
        try {
            oc.carregarDetalhes(cbDescricao);
        } catch (SQLException ex) {
            Logger.getLogger(MovOrcamneto.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnaddDetalheActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
       sc.limpar(jPanel1.getComponents());
       sc.HabilityComponents(jPanel1.getComponents(), false);
       sc.Initialize(jPanel2.getComponents());
       sc.limparTabela(jTable1);
       sc.limparTabela(jTable2);
       flag = true;
       linha = -1;
       oc.clearSequenceNumber();
       oc.limpaLista();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void txtValorFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtValorFocusGained
        txtValor_total.setText(""+oc.calcular(txtValor.getText(), String.valueOf(spQtd.getValue()), txtCustoP.getText(), txtCustoI.getText(), txtCustoAcab.getText(), txtCustoArt.getText(), txtCustoChap.getText(), txtCustoMdO.getText(), txtDesconto.getText()));
    }//GEN-LAST:event_txtValorFocusGained

    private void spQtdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_spQtdFocusGained
        if(v.ConverteNumeroInteiro(spQtd.getValue()) < 0)
        {
            spQtd.setValue(sc.removeCharacter(String.valueOf(spQtd.getValue()), String.valueOf(spQtd.getValue()).length()-1));
        }
        txtValor_total.setText(""+oc.calcular(txtValor.getText(), String.valueOf(spQtd.getValue()), txtCustoP.getText(), txtCustoI.getText(), txtCustoAcab.getText(), txtCustoArt.getText(), txtCustoChap.getText(), txtCustoMdO.getText(), txtDesconto.getText()));
    }//GEN-LAST:event_spQtdFocusGained

    private void txtCustoPFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCustoPFocusGained
        txtValor_total.setText(""+oc.calcular(txtValor.getText(), String.valueOf(spQtd.getValue()), txtCustoP.getText(), txtCustoI.getText(), txtCustoAcab.getText(), txtCustoArt.getText(), txtCustoChap.getText(), txtCustoMdO.getText(), txtDesconto.getText()));
    }//GEN-LAST:event_txtCustoPFocusGained

    private void txtCustoIFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCustoIFocusGained
        txtValor_total.setText(""+oc.calcular(txtValor.getText(), String.valueOf(spQtd.getValue()), txtCustoP.getText(), txtCustoI.getText(), txtCustoAcab.getText(), txtCustoArt.getText(), txtCustoChap.getText(), txtCustoMdO.getText(), txtDesconto.getText()));
    }//GEN-LAST:event_txtCustoIFocusGained

    private void txtCustoAcabFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCustoAcabFocusGained
        txtValor_total.setText(""+oc.calcular(txtValor.getText(), String.valueOf(spQtd.getValue()), txtCustoP.getText(), txtCustoI.getText(), txtCustoAcab.getText(), txtCustoArt.getText(), txtCustoChap.getText(), txtCustoMdO.getText(), txtDesconto.getText()));
    }//GEN-LAST:event_txtCustoAcabFocusGained

    private void txtCustoArtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCustoArtFocusGained
        txtValor_total.setText(""+oc.calcular(txtValor.getText(), String.valueOf(spQtd.getValue()), txtCustoP.getText(), txtCustoI.getText(), txtCustoAcab.getText(), txtCustoArt.getText(), txtCustoChap.getText(), txtCustoMdO.getText(), txtDesconto.getText()));
    }//GEN-LAST:event_txtCustoArtFocusGained

    private void txtCustoChapFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCustoChapFocusGained
        txtValor_total.setText(""+oc.calcular(txtValor.getText(), String.valueOf(spQtd.getValue()), txtCustoP.getText(), txtCustoI.getText(), txtCustoAcab.getText(), txtCustoArt.getText(), txtCustoChap.getText(), txtCustoMdO.getText(), txtDesconto.getText()));
    }//GEN-LAST:event_txtCustoChapFocusGained

    private void txtCustoMdOFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCustoMdOFocusGained
        txtValor_total.setText(""+oc.calcular(txtValor.getText(), String.valueOf(spQtd.getValue()), txtCustoP.getText(), txtCustoI.getText(), txtCustoAcab.getText(), txtCustoArt.getText(), txtCustoChap.getText(), txtCustoMdO.getText(), txtDesconto.getText()));
    }//GEN-LAST:event_txtCustoMdOFocusGained

    private void txtDescontoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDescontoFocusGained
        txtValor_total.setText(""+oc.calcular(txtValor.getText(), String.valueOf(spQtd.getValue()), txtCustoP.getText(), txtCustoI.getText(), txtCustoAcab.getText(), txtCustoArt.getText(), txtCustoChap.getText(), txtCustoMdO.getText(), txtDesconto.getText()));
    }//GEN-LAST:event_txtDescontoFocusGained

    private void txtValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValorActionPerformed
       txtValor.setText("");
    }//GEN-LAST:event_txtValorActionPerformed

    private void txtCustoPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCustoPActionPerformed
        txtCustoP.setText("");
    }//GEN-LAST:event_txtCustoPActionPerformed

    private void txtCustoIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCustoIActionPerformed
      txtCustoI.setText("");
    }//GEN-LAST:event_txtCustoIActionPerformed

    private void txtCustoAcabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCustoAcabActionPerformed
       txtCustoAcab.setText("");
    }//GEN-LAST:event_txtCustoAcabActionPerformed

    private void txtCustoArtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCustoArtActionPerformed
        txtCustoArt.setText("");
    }//GEN-LAST:event_txtCustoArtActionPerformed

    private void txtCustoChapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCustoChapActionPerformed
        txtCustoChap.setText("");
    }//GEN-LAST:event_txtCustoChapActionPerformed

    private void txtCustoMdOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCustoMdOActionPerformed
       txtCustoMdO.setText("");
    }//GEN-LAST:event_txtCustoMdOActionPerformed

    private void txtDescontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescontoActionPerformed
        txtDesconto.setText("");
    }//GEN-LAST:event_txtDescontoActionPerformed

    private void btnAddServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddServicoActionPerformed
     switch(oc.varidarAddServico(txtServico.getText(), txtValor.getText(), String.valueOf(spQtd.getValue()), txtCustoP.getText(), txtCustoI.getText(), txtCustoAcab.getText(), txtCustoArt.getText(), txtCustoChap.getText(), txtCustoMdO.getText(), txtDescricao.getText(), txtDesconto.getText(), linha, txtValor_total.getText()))
     {
         case 1: m.InformationMessage("Informe o Serviço!", "Atenção"); btnlocServico.requestFocus(); break;
         case 2: m.InformationMessage("Informe a Quantidade!", "Atenção"); spQtd.requestFocus(); break;
         case 3: m.InformationMessage("Informe o Valor!", "Atenção"); txtValor.requestFocus(); break;
         case 4: m.InformationMessage("Informe os Valores!", "Atenção"); break;
         case 5: m.InformationMessage("Custo do papel deve ser maior ou igual a 0!", "Atenção"); txtCustoP.requestFocus(); break;
         case 6: m.InformationMessage("Custo da Impressão deve ser maior ou igual a 0!", "Atenção"); txtCustoI.requestFocus(); break;
         case 7: m.InformationMessage("Custo do acabamento deve ser maior ou igual a 0!", "Atenção"); txtCustoAcab.requestFocus(); break;
         case 8: m.InformationMessage("Custo da arte deve ser maior ou igual a 0!", "Atenção"); txtCustoArt.requestFocus(); break;
         case 9: m.InformationMessage("Custo da chapa deve ser maior ou igual a 0!", "Atenção"); txtCustoChap.requestFocus(); break;
         case 10: m.InformationMessage("Custo da mão de obra deve ser maior ou igual a 0!", "Atenção"); txtCustoMdO.requestFocus(); break;
         case 11: m.InformationMessage("Desconto deve ser maior ou igual a 0!", "Atenção"); txtDesconto.requestFocus(); break;
         default: 
             oc.addTabelaServico(jTable1, linha);
             txtValorT.setText(""+oc.calculoTotal(jTable1));
             linha = -1;
             //Limpar os campo
     }
    }//GEN-LAST:event_btnAddServicoActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        linha = -1;
        flag = true;
        sc.HabilityComponents(jPanel1.getComponents(), true);
        sc.HabilityComponents(jPanel4.getComponents(), false);
        sc.Edity(jPanel2.getComponents());
        txtValorT.setText("0");
        txtCodigo.setText("0");
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnAlterarServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarServicoActionPerformed
        if (jTable1.getSelectedRow() >= 0)
        {
      //      sc.HabilityComponents(jPanel4.getComponents(), true);
            linha = jTable1.getSelectedRow();
            //テキストフィールドにデーターを追加。 追加済み↓2019/06/27
            ReadOnlyTableModel model = (ReadOnlyTableModel) jTable1.getModel();
            txtServico.setText(""+model.getValueAt(jTable1.getSelectedRow(), 0));
            txtValor.setText(""+sc.verificaValor(sc.converteString(model.getValueAt(jTable1.getSelectedRow(), 1))));
            spQtd.setValue(model.getValueAt(jTable1.getSelectedRow(), 2));
            txtCustoP.setText(""+sc.verificaValor(sc.converteString(model.getValueAt(jTable1.getSelectedRow(), 3))));
            txtCustoArt.setText(""+sc.verificaValor(sc.converteString(model.getValueAt(jTable1.getSelectedRow(), 4))));
            txtCustoI.setText(""+sc.verificaValor(sc.converteString(model.getValueAt(jTable1.getSelectedRow(), 5))));
            txtCustoAcab.setText(""+sc.verificaValor(sc.converteString(model.getValueAt(jTable1.getSelectedRow(), 6))));
            txtCustoChap.setText(""+sc.verificaValor(sc.converteString(model.getValueAt(jTable1.getSelectedRow(), 7))));
            txtCustoMdO.setText(""+sc.verificaValor(sc.converteString(model.getValueAt(jTable1.getSelectedRow(), 8))));
            txtDesconto.setText(""+sc.verificaValor(sc.converteString(model.getValueAt(jTable1.getSelectedRow(), 9))));
            txtValor_total.setText(""+sc.verificaValor(sc.converteString(model.getValueAt(jTable1.getSelectedRow(), 10))));
            txtDescricao.setText(""+sc.verificaValor(sc.converteString(model.getValueAt(jTable1.getSelectedRow(), 11))));
        }
        else
        {
         //   sc.HabilityComponents(jPanel4.getComponents(), false);
            m.InformationMessage("Você deve selecionar um registro", "Informação");
        }
    }//GEN-LAST:event_btnAlterarServicoActionPerformed

    private void btnExcluirServiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirServiActionPerformed
        if(oc.excluirServico(jTable1, jTable1.getSelectedRow(), flag))
        {
            m.InformationMessage("Excluido com Sucesso", "Informação");
            txtValorT.setText(""+oc.calculoTotal(jTable1));
        }
    }//GEN-LAST:event_btnExcluirServiActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       switch(oc.varidarAddServicoDetalhe((String) cbDescricao.getSelectedItem(), txtNumeracaoI.getText(), txtNumeracaoF.getText(), txtVia.getText(), txtOutros.getText(), jTable2, jTable1.getSelectedRow(), 0))
       {
           case 1: m.InformationMessage("Informe a numeração Inicial", "Informação"); txtNumeracaoI.requestFocus(); break;
           case 2: m.InformationMessage("Informe a numeração Final", "Informação"); txtNumeracaoF.requestFocus(); break;
           case 3: m.InformationMessage("A numeração Inicial deve ser maior que 0", "Informação"); txtNumeracaoI.requestFocus(); break;
           case 4: m.InformationMessage("A numeração Final deve ser maior que 0", "Informação"); txtNumeracaoF.requestFocus(); break;
           case 5: m.InformationMessage("A numeração Inicail não deve ser menor que a numeração Final", "Informação"); txtNumeracaoI.requestFocus(); break;
           case 6: m.InformationMessage("Informe a quantidade de Via(s)", "Informação"); txtVia.requestFocus(); break;
           case 7: m.InformationMessage("A quantidade de Via(s) não pode ser menor ou igual a 0", "Informação"); txtVia.requestFocus(); break;
           case 8: m.InformationMessage("Informe o campo Outros", "Informação"); txtOutros.requestFocus(); break;
           case 9: m.InformationMessage("Detalhe ja inserido!", "Informação"); break;
           default:
               oc.addTabelaServicoDetalhe(jTable2, jTable1.getSelectedRow());
               startDescricao();
       }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        oc.excluirDetalheServico(jTable2, jTable1.getSelectedRow(), jTable2.getSelectedRow(), flag, txtCodigo.getText());
        startDescricao();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        if (jTable1.getSelectedRow() >= 0)
        {
            sc.limparTabela(jTable2);
            sc.HabilityComponents(jPanel4.getComponents(), true);
            oc.carregarTabelaDetalheServico(jTable2, jTable1.getSelectedRow());
            startDescricao();
            cbDescricao.requestFocus();
            cbDescricaoActionPerformed(null);
        }
        else
        {
            sc.HabilityComponents(jPanel4.getComponents(), false);
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
//        if (jTable1.getSelectedRow() >= 0)
//        {
//            sc.HabilityComponents(jPanel4.getComponents(), true);
//        }
//        else
//        {
//            sc.HabilityComponents(jPanel4.getComponents(), false);
//        }
    }//GEN-LAST:event_jTable2MouseClicked

    private void btnGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGravarActionPerformed
        try {
            switch(oc.varidarOrcamento(txtCodigo.getText(), txtCliente.getText(), (String) cbForma.getSelectedItem(), txtValorT.getText(), dcDataPedido.getData(), dcDataVencimento.getData()))
            {
                case 1: m.InformationMessage("Informe o Cliente!", "Atenção"); btnlocCliente.requestFocus(); break;
                case 2: m.InformationMessage("Informe o(s) Serviço(s)!", "Atenção"); btnlocServico.requestFocus(); break;
                case 3: m.InformationMessage("A data de vencimetno é inferior a data do Orçamento!", "Atenção");
                default:
                    if(flag)
                    {
                        if(oc.gravarOrcamento())
                        {
                            oc.UpdateNumberOrcamento();
                            if(oc.gravarOrcemntoServico())
                                if(oc.gravarOrcamentoServicoDetalhe())
                                {
                                    m.InformationMessage("Gravado com Sucesso", "Informação");
                                    sc.limpar(jPanel1.getComponents());
                                    sc.limparTabela(jTable1);
                                    sc.limparTabela(jTable2);
                                    sc.HabilityComponents(jPanel1.getComponents(), false);
                                    //flag = true;
                                    linha = -1;
                                    oc.limpaLista();
                                    oc.clearSequenceNumber();
                                    sc.Initialize(jPanel2.getComponents());
                                }
//                                else
//                                    m.ErroMessage("ERRO", "ERRO3");
//                            else
//                             m.ErroMessage("ERRO", "ERRO2");   
                        }
                        else
                        {
                            m.ErroMessage("ERRO", "ERRO1");
                        }
                        
                    }
                    else
                    {
                        if(oc.gravarOrcamento())
                        {
                            oc.excluirListas(Integer.parseInt(txtCodigo.getText()));
                            oc.alterarOrcamentoServico();
                            oc.alterarOrcamentoServicoDetalhe();
                            m.InformationMessage("Alterado com Sucesso", "Informação");
                            sc.limpar(jPanel1.getComponents());
                            oc.limpaLista();
                            sc.limparTabela(jTable1);
                            sc.limparTabela(jTable2);
                            sc.HabilityComponents(jPanel1.getComponents(), false);
                            flag = true;
                            linha = -1;
                            oc.clearSequenceNumber();
                            sc.Initialize(jPanel2.getComponents());
                                
//                                else
//                                    m.ErroMessage("ERRO1", "ERRO3");
//                            else
//                             m.ErroMessage("ERRO2", "ERRO2");   
                        }
                        else
                        {
                            m.ErroMessage("ERRO1", "ERRO1");
                        }
                    }
            }
        } catch (SQLException ex) {
            Logger.getLogger(MovOrcamneto.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnGravarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        if(m.Pergunta("Deseja excluir esse Orçamento?", "Atenção") == JOptionPane.YES_OPTION)
        {
            if(oc.excluirOrcamento(Integer.parseInt(txtCodigo.getText())))
            {
                m.InformationMessage("Excluido com Sucesso!", "Informação");
                sc.limpar(jPanel1.getComponents());
                oc.limpaLista();
                sc.limparTabela(jTable1);
                sc.limparTabela(jTable2);
                sc.Initialize(jPanel2.getComponents());
            }
            else
                m.ErroMessage("Erro ao Excluir! Provavelmente esta sendo usado em Pedido ou em alguma outra Tabela!", "Erro");
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnLocalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLocalizarActionPerformed
        ConsultaMov consOrcamento = new ConsultaMov(null, true);
        String[] vet = new String[4];
        vet[0] = "Tudo";
        vet[1] = "Data";
        vet[2] = "Periodo";
        vet[3] = "Numero";
        consOrcamento.configuraOpcoes(vet, 4, 0, "Orçamento", false);
        consOrcamento.verificaconsulta(true);
        consOrcamento.setVisible(true);
        if (consOrcamento.getCodigo() != 0)
        {
            txtCodigo.setText(String.valueOf(consOrcamento.getCodigo()));
            consOrcamento.dispose();
            txtCodigoFocusLost(null);
            sc.Alter(jPanel2.getComponents());
        }
        else
        {
            consOrcamento.dispose();
            btnLocalizar.requestFocus();
        }
    }//GEN-LAST:event_btnLocalizarActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        flag = false;
        sc.HabilityComponents(jPanel1.getComponents(), true);
        sc.HabilityComponents(jPanel4.getComponents(), false);
        sc.Edity(jPanel2.getComponents());
        linha = -1;
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void txtCodigoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCodigoFocusLost
        if(!txtCodigo.getText().equals("0"))
        {
            try {
                oc.buscarDados(Integer.parseInt(txtCodigo.getText()));
            } catch (SQLException ex) {
                Logger.getLogger(MovOrcamneto.class.getName()).log(Level.SEVERE, null, ex);
            }
            if(oc.getO() != null)
            {
                txtCodigo.setText(""+oc.getO().getCodigo());
                txtCliente.setText(""+oc.getO().getCli().getNome());
                txtValorT.setText(""+oc.getO().getValorTotal());
                dcDataPedido.setData(oc.getO().getOrcado());
                dcDataVencimento.setData(oc.getO().getValidade());
                cbForma.setSelectedItem(oc.getO().getFp().getNome());
                oc.carregarTabelaServico(jTable1);
                oc.carregarTabelaDetalheServico(jTable2, 0);
            }
        }
    }//GEN-LAST:event_txtCodigoFocusLost

    private void txtValorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtValorFocusLost
        txtValor_total.setText(""+oc.calcular(txtValor.getText(), String.valueOf(spQtd.getValue()), txtCustoP.getText(), txtCustoI.getText(), txtCustoAcab.getText(), txtCustoArt.getText(), txtCustoChap.getText(), txtCustoMdO.getText(), txtDesconto.getText()));
    }//GEN-LAST:event_txtValorFocusLost

    private void spQtdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_spQtdFocusLost
        txtValor_total.setText(""+oc.calcular(txtValor.getText(), String.valueOf(spQtd.getValue()), txtCustoP.getText(), txtCustoI.getText(), txtCustoAcab.getText(), txtCustoArt.getText(), txtCustoChap.getText(), txtCustoMdO.getText(), txtDesconto.getText()));
    }//GEN-LAST:event_spQtdFocusLost

    private void txtCustoPFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCustoPFocusLost
        txtValor_total.setText(""+oc.calcular(txtValor.getText(), String.valueOf(spQtd.getValue()), txtCustoP.getText(), txtCustoI.getText(), txtCustoAcab.getText(), txtCustoArt.getText(), txtCustoChap.getText(), txtCustoMdO.getText(), txtDesconto.getText()));
    }//GEN-LAST:event_txtCustoPFocusLost

    private void txtCustoIFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCustoIFocusLost
        txtValor_total.setText(""+oc.calcular(txtValor.getText(), String.valueOf(spQtd.getValue()), txtCustoP.getText(), txtCustoI.getText(), txtCustoAcab.getText(), txtCustoArt.getText(), txtCustoChap.getText(), txtCustoMdO.getText(), txtDesconto.getText()));
    }//GEN-LAST:event_txtCustoIFocusLost

    private void txtCustoAcabFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCustoAcabFocusLost
        txtValor_total.setText(""+oc.calcular(txtValor.getText(), String.valueOf(spQtd.getValue()), txtCustoP.getText(), txtCustoI.getText(), txtCustoAcab.getText(), txtCustoArt.getText(), txtCustoChap.getText(), txtCustoMdO.getText(), txtDesconto.getText()));
    }//GEN-LAST:event_txtCustoAcabFocusLost

    private void txtCustoArtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCustoArtFocusLost
        txtValor_total.setText(""+oc.calcular(txtValor.getText(), String.valueOf(spQtd.getValue()), txtCustoP.getText(), txtCustoI.getText(), txtCustoAcab.getText(), txtCustoArt.getText(), txtCustoChap.getText(), txtCustoMdO.getText(), txtDesconto.getText()));
    }//GEN-LAST:event_txtCustoArtFocusLost

    private void txtCustoChapFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCustoChapFocusLost
        txtValor_total.setText(""+oc.calcular(txtValor.getText(), String.valueOf(spQtd.getValue()), txtCustoP.getText(), txtCustoI.getText(), txtCustoAcab.getText(), txtCustoArt.getText(), txtCustoChap.getText(), txtCustoMdO.getText(), txtDesconto.getText()));
    }//GEN-LAST:event_txtCustoChapFocusLost

    private void txtCustoMdOFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCustoMdOFocusLost
        txtValor_total.setText(""+oc.calcular(txtValor.getText(), String.valueOf(spQtd.getValue()), txtCustoP.getText(), txtCustoI.getText(), txtCustoAcab.getText(), txtCustoArt.getText(), txtCustoChap.getText(), txtCustoMdO.getText(), txtDesconto.getText()));
    }//GEN-LAST:event_txtCustoMdOFocusLost

    private void txtDescontoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDescontoFocusLost
        txtValor_total.setText(""+oc.calcular(txtValor.getText(), String.valueOf(spQtd.getValue()), txtCustoP.getText(), txtCustoI.getText(), txtCustoAcab.getText(), txtCustoArt.getText(), txtCustoChap.getText(), txtCustoMdO.getText(), txtDesconto.getText()));
    }//GEN-LAST:event_txtDescontoFocusLost

    private void cbDescricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbDescricaoActionPerformed
        enableComponents(String.valueOf(cbDescricao.getSelectedItem()));
    }//GEN-LAST:event_cbDescricaoActionPerformed

    private void cbDescricaoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cbDescricaoFocusLost
        enableComponents(String.valueOf(cbDescricao.getSelectedItem()));
    }//GEN-LAST:event_cbDescricaoFocusLost

    private void clearLocalComponents()
    {
        txtCustoAcab.setText("0");
        txtCustoArt.setText("0");
        txtCustoChap.setText("0");
        txtCustoI.setText("0");
        txtCustoMdO.setText("0");
        txtCustoP.setText("0");
        txtDesconto.setText("0");
        txtValor.setText("0");
        spQtd.setValue("0");
    }
    
    private void startDescricao()
    {
        txtNumeracaoI.setText("0");
        txtNumeracaoF.setText("0");
        txtOutros.setText("");
        txtVia.setText("0");
    }
    
    private void enableComponents(String valor)
    {
        switch(valor.toUpperCase())
        {
            case "NUMERAÇÃO": txtNumeracaoI.setEnabled(true); txtNumeracaoF.setEnabled(true); txtVia.setEnabled(false); txtOutros.setEnabled(false); labelTexto1.setFont(new Font("Arial", Font.BOLD, 14)); labelTexto2.setFont(new Font("Arial", Font.PLAIN, 14)); labelTexto3.setFont(new Font("Arial", Font.PLAIN, 14)); break;
            case "OUTROS": txtNumeracaoI.setEnabled(false); txtNumeracaoF.setEnabled(false); txtVia.setEnabled(false); txtOutros.setEnabled(true); labelTexto1.setFont(new Font("Arial", Font.PLAIN, 14)); labelTexto2.setFont(new Font("Arial", Font.PLAIN, 14)); labelTexto3.setFont(new Font("Arial", Font.BOLD, 14)); break;
            case "VIAS": txtNumeracaoI.setEnabled(false); txtNumeracaoF.setEnabled(false); txtVia.setEnabled(true); txtOutros.setEnabled(false); labelTexto1.setFont(new Font("Arial", Font.PLAIN, 14)); labelTexto2.setFont(new Font("Arial", Font.BOLD, 14)); labelTexto3.setFont(new Font("Arial", Font.PLAIN, 14)); break;
            default:
                txtNumeracaoI.setEnabled(false); txtNumeracaoF.setEnabled(false); txtVia.setEnabled(false); txtOutros.setEnabled(false);
                labelTexto1.setFont(new Font("Arial", Font.PLAIN, 14)); labelTexto2.setFont(new Font("Arial", Font.PLAIN, 14)); labelTexto3.setFont(new Font("Arial", Font.PLAIN, 14));
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LCodigoServi;
    private javax.swing.JButton btnAddServico;
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnAlterarServico;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnExcluirServi;
    private javax.swing.JButton btnGravar;
    private javax.swing.JButton btnLocalizar;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnPDF;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnaddCliente;
    private javax.swing.JButton btnaddDetalhe;
    private javax.swing.JButton btnaddServico;
    private javax.swing.JButton btnlocCliente;
    private javax.swing.JButton btnlocServico;
    private javax.swing.JComboBox<String> cbDescricao;
    private javax.swing.JComboBox<String> cbForma;
    private br.com.marciorl.beans.DateChooser dcDataPedido;
    private br.com.marciorl.beans.DateChooser dcDataVencimento;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel labelTexto1;
    private javax.swing.JLabel labelTexto2;
    private javax.swing.JLabel labelTexto3;
    private javax.swing.JSpinner spQtd;
    private javax.swing.JTextField txtCliente;
    private javax.swing.JTextField txtCodigo;
    private br.com.ikeda.beans.jTextFieldMonetario txtCustoAcab;
    private br.com.ikeda.beans.jTextFieldMonetario txtCustoArt;
    private br.com.ikeda.beans.jTextFieldMonetario txtCustoChap;
    private br.com.ikeda.beans.jTextFieldMonetario txtCustoI;
    private br.com.ikeda.beans.jTextFieldMonetario txtCustoMdO;
    private br.com.ikeda.beans.jTextFieldMonetario txtCustoP;
    private javax.swing.JTextField txtDescServi;
    private br.com.ikeda.beans.jTextFieldMonetario txtDesconto;
    private javax.swing.JTextArea txtDescricao;
    private javax.swing.JTextField txtNumeracaoF;
    private javax.swing.JTextField txtNumeracaoI;
    private javax.swing.JTextField txtOutros;
    private javax.swing.JTextField txtServico;
    private br.com.ikeda.beans.jTextFieldMonetario txtValor;
    private javax.swing.JTextField txtValorT;
    private javax.swing.JTextField txtValor_total;
    private javax.swing.JTextField txtVia;
    // End of variables declaration//GEN-END:variables
}
