package CamadaApresentacao;

import CamadaLogica.ReadOnlyTableModel;
import CamadaNegocio.Funcionario;
import Controller.ProducaoController;
import Controller.ProdutoController;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import util.SystemControl;
import util.mensagens;

/**
 *
 * @author 吉野　廉
 * @author 羽根川　翼
 * @author モニカ
 * @author 巴御前
 * @author 高村　結衣
 * @author 里川　麗奈
 * @author 橋立
 * @author 阿賀野
 * @author 矢矧
 * 
 * Tester 2019年07月28日
 * @author 曙
 * @author 漣
 * @author 能代
 */
public class MovProducao extends javax.swing.JDialog {

    private final SystemControl sc = new SystemControl();
    private final mensagens m = new mensagens();
    private final ProducaoController pc = new ProducaoController();

    public MovProducao(java.awt.Frame parent, boolean modal, Funcionario f) {
        super(parent, false);
        initComponents();
        setLocationRelativeTo(null);
        ProducaoController.configuraModelTabela1(jTable1);
        ProducaoController.configuraModelTabela2(jTable2);
        ProducaoController.configuraModelTabela3(jTable3);
        
        btnAlterar.setName("btnAlterar");
        btnCancelar.setName("btnCancelar");
        btnGravar.setName("btnGravar");
        btnSair.setName("btnSair");
        btnaddFolha.setName("btnaddFolha");
        btnlocFolha.setName("btnlocFolha");
        btnaddFuncionario.setName("btnaddFuncionario");
        btnlocFuncionario.setName("btnlocFuncionario");
        btnaddFolha.setName("btnaddFolha");
        btnlocFolha.setText("btnlocFolha");
        btnaddProduto.setText("btnaddProduto");
        btnlocProduto.setText("btnlocProduto");
        pc.getP().setF(f);
        txtFuncionario.setText(""+f.getNome());
        sc.Initialize(jPanel3.getComponents());
        sc.HabilityComponents(jPanel2.getComponents(), false);
        sc.HabilityComponents(jPanel4.getComponents(), false);
        pc.carregarListaCliente(1, "", jTable1);
    }
/*
    Rog:
    2019年07月03日：
        今日の担当：吉野　廉、　羽根川　翼、　里川　麗奈、　阿賀野
        明日の仕事：MovProducao及びその他のメッソッドの終了。　
    
    2019年07月04日：
        今日の担当：吉野　廉、　羽根川　翼、　阿賀野, 矢矧
        明日の仕事：MovProducao及びその他のメッソッドの終了。
        今日のメモ：　里川　麗奈　ふざけるな！どうやって、何をすれば今日中に終わるんだよ？
    
    2019年07月08日：
        今日の担当：吉野　廉、　羽根川　翼、　モニカ、　橋立
        今日のメモ：　まだ別のJDialog（詳細）を呼んでいないが通常機能はすべて終了。
    
    2019年07月21日：
        今日の担当：吉野　廉、　羽根川　翼、　モニカ、　高村　結衣、　里川　麗奈
        今日のメモ：　JDialog（詳細）の処理。完了。テスト待機中。
    */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        rbClienteOP2 = new javax.swing.JRadioButton();
        rbClienteOP3 = new javax.swing.JRadioButton();
        txtFiltro = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtOBS = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        rbPedidoOP3 = new javax.swing.JRadioButton();
        rbPedidoOP2 = new javax.swing.JRadioButton();
        txtFuncionario = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        btnlocFuncionario = new javax.swing.JButton();
        btnaddFuncionario = new javax.swing.JButton();
        cbStatus = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        btnAlterar = new javax.swing.JButton();
        btnGravar = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        txtProduto = new javax.swing.JTextField();
        txtQtdP = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnaddProduto = new javax.swing.JButton();
        btnlocProduto = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtEstoqueP = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtEstoqueF = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtQtdF = new javax.swing.JTextField();
        txtFolha = new javax.swing.JTextField();
        btnaddFolha = new javax.swing.JButton();
        btnlocFolha = new javax.swing.JButton();
        btnadd = new javax.swing.JButton();
        btnexcluir = new javax.swing.JButton();
        btnremoveAll = new javax.swing.JButton();
        txtReservadoP = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtReservadoF = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Cliente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 11))); // NOI18N

        jTable1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        rbClienteOP2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        rbClienteOP2.setSelected(true);
        rbClienteOP2.setText("Serviço a fazer");
        rbClienteOP2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbClienteOP2MouseClicked(evt);
            }
        });
        rbClienteOP2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbClienteOP2ActionPerformed(evt);
            }
        });

        rbClienteOP3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        rbClienteOP3.setText("Serviços prontos não entregue");
        rbClienteOP3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbClienteOP3MouseClicked(evt);
            }
        });
        rbClienteOP3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbClienteOP3ActionPerformed(evt);
            }
        });

        txtFiltro.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtFiltro.setText("Nome Cliente ou Numero pedido");
        txtFiltro.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtFiltroFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFiltroFocusLost(evt);
            }
        });
        txtFiltro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFiltroKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(rbClienteOP2)
                        .addGap(18, 18, 18)
                        .addComponent(rbClienteOP3, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtFiltro))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 782, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbClienteOP2)
                    .addComponent(rbClienteOP3)
                    .addComponent(txtFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Pedido", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 11))); // NOI18N

        jTable2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setText("Observação do pedido selecionado:");

        txtOBS.setEditable(false);
        txtOBS.setColumns(20);
        txtOBS.setRows(5);
        jScrollPane3.setViewportView(txtOBS);

        jLabel9.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel9.setText("Status:");

        rbPedidoOP3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        rbPedidoOP3.setSelected(true);
        rbPedidoOP3.setText("Pedidos ainda não entregue");
        rbPedidoOP3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbPedidoOP3MouseClicked(evt);
            }
        });
        rbPedidoOP3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbPedidoOP3ActionPerformed(evt);
            }
        });

        rbPedidoOP2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        rbPedidoOP2.setText("Pedidos ja entregue");
        rbPedidoOP2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbPedidoOP2MouseClicked(evt);
            }
        });
        rbPedidoOP2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbPedidoOP2ActionPerformed(evt);
            }
        });

        txtFuncionario.setEditable(false);

        jLabel12.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel12.setText("Funcionario Responsavel:");

        btnlocFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Localizar 16.png"))); // NOI18N
        btnlocFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlocFuncionarioActionPerformed(evt);
            }
        });

        btnaddFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Novo 16.png"))); // NOI18N
        btnaddFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddFuncionarioActionPerformed(evt);
            }
        });

        cbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pronto", "Pausado", "Desenvolvomento", "Aguardando" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addComponent(btnaddFuncionario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnlocFuncionario))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(rbPedidoOP3)
                                .addGap(18, 18, 18)
                                .addComponent(rbPedidoOP2)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cbStatus, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbPedidoOP2)
                    .addComponent(rbPedidoOP3))
                .addGap(7, 7, 7)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel12))
                            .addComponent(btnaddFuncionario))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(cbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnlocFuncionario)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnAlterar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Alterar16.png"))); // NOI18N
        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnGravar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnGravar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Gravar16.png"))); // NOI18N
        btnGravar.setText("Gravar");
        btnGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGravarActionPerformed(evt);
            }
        });

        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Sair.png"))); // NOI18N
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Cancelar16.png.jpg"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 821, Short.MAX_VALUE)
                .addComponent(btnGravar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAlterar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSair, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGravar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Itens", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 11))); // NOI18N

        jTable3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane4.setViewportView(jTable3);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setText("Produto:");

        txtProduto.setEditable(false);

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setText("Quantidade:");

        btnaddProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Novo 16.png"))); // NOI18N
        btnaddProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddProdutoActionPerformed(evt);
            }
        });

        btnlocProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Localizar 16.png"))); // NOI18N
        btnlocProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlocProdutoActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setText("Qtd no estoque:");

        txtEstoqueP.setEditable(false);

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setText("Folha:");

        jLabel7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel7.setText("Qtd no estoque:");

        txtEstoqueF.setEditable(false);

        jLabel8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel8.setText("Quantidade:");

        txtFolha.setEditable(false);

        btnaddFolha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Novo 16.png"))); // NOI18N
        btnaddFolha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddFolhaActionPerformed(evt);
            }
        });

        btnlocFolha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Localizar 16.png"))); // NOI18N
        btnlocFolha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlocFolhaActionPerformed(evt);
            }
        });

        btnadd.setText("Adicionar");
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });

        btnexcluir.setText("Excluir");
        btnexcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexcluirActionPerformed(evt);
            }
        });

        btnremoveAll.setText("Remover todos Itens");
        btnremoveAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnremoveAllActionPerformed(evt);
            }
        });

        txtReservadoP.setEditable(false);

        jLabel10.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel10.setText("Qtd Reservado:");

        jLabel11.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel11.setText("Qtd Reservado:");

        txtReservadoF.setEditable(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtEstoqueP, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtQtdP, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtReservadoP, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtEstoqueF, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtQtdF, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtReservadoF, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnaddProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnlocProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(btnadd)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnexcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnremoveAll))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtFolha, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(btnaddFolha, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnlocFolha, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(txtProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnlocProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnaddProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(txtReservadoP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(txtQtdP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtEstoqueP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(txtFolha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnlocFolha, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnaddFolha, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(txtReservadoF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(txtQtdF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtEstoqueF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7)))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnexcluir)
                    .addComponent(btnadd)
                    .addComponent(btnremoveAll))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        sc.limparTabela(jTable2);
        if(jTable1.getSelectedRow() >= 0)
        {
            //System.out.println("Teste1: "+jTable1.getSelectedRow());
            if(evt.getClickCount() == 1)
            {
//                jTable2.removeAll();
                sc.HabilityComponents(jPanel2.getComponents(), true);
                sc.Alter(jPanel3.getComponents());
                //carregar os Itens de pedido OK
                ReadOnlyTableModel model = (ReadOnlyTableModel) jTable1.getModel();
                pc.carregarListaPedido(rbPedidoOP2.isSelected() ? 1 : 2, jTable2, Integer.valueOf(String.valueOf(model.getValueAt(jTable1.getSelectedRow(), 2))));
            }    
        }
        else
        {
             sc.HabilityComponents(jPanel2.getComponents(), false);
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        ReadOnlyTableModel model = (ReadOnlyTableModel) jTable2.getModel();
        if(jTable2.getSelectedRow() >= 0)
        {
            if(evt.getClickCount() == 1)
            {
//              jTable3.removeAll();
                sc.limparTabela(jTable3);
                sc.HabilityComponents(jPanel4.getComponents(), true);
                sc.Alter(jPanel3.getComponents());
                //carregar os Itens Folha e produto  OK 
                pc.carregarListaItens(Integer.valueOf(String.valueOf(model.getValueAt(jTable2.getSelectedRow(), 0))), jTable3);
                sc.Edity(jPanel3.getComponents());
            }
            else
            {
                //OK Creating new form for DetalheServico.  OK
                CheckDetalheServico formCDS;
                try {
                    formCDS = new CheckDetalheServico(null, false, Integer.valueOf(String.valueOf(model.getValueAt(jTable2.getSelectedRow(), 0))));
                    formCDS.setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(MovProducao.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
        else
        {
            sc.Initialize(jPanel3.getComponents());
            sc.HabilityComponents(jPanel4.getComponents(), false);
        }
    }//GEN-LAST:event_jTable2MouseClicked

    private void btnaddFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddFuncionarioActionPerformed
        CadastroFuncionario frm = new CadastroFuncionario(null, true, false);
        frm.setTitle("Cadastro Funcionario");
        frm.setVisible(true);
    }//GEN-LAST:event_btnaddFuncionarioActionPerformed

    private void btnlocFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlocFuncionarioActionPerformed
        ConsultaPadrao consFuncionario = new ConsultaPadrao(null, true);
        String[] vet = new String[2];
        vet[0] = "Nome";
        vet[1] = "CPF";
        consFuncionario.configuraOpcoes(vet, 2, 1, "Funcionario", false);
        consFuncionario.verificaconsulta(true);
        consFuncionario.setVisible(true);
        if (consFuncionario.getCodigo() != 0)
        {
            pc.buscarFuncionario(consFuncionario.getCodigo());
            txtFuncionario.setText(""+pc.getP().getF().getNome());
            consFuncionario.dispose();
        }
        else
        {
            consFuncionario.dispose();
        }
    }//GEN-LAST:event_btnlocFuncionarioActionPerformed

    private void btnaddProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddProdutoActionPerformed
       CadastroProduto frm = new CadastroProduto(null, true);
       frm.setTitle("Cadastro Produto");
       frm.setVisible(true);
    }//GEN-LAST:event_btnaddProdutoActionPerformed

    private void btnlocProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlocProdutoActionPerformed
        ConsultaPadrao consP = new ConsultaPadrao(null, true);
        String[] vet = new String[2];
        vet[0] = "Tamanho";
        vet[1] = "Descrição";
        consP.configuraOpcoes(vet, 2, 0, "AProduto", false);
        consP.verificaconsulta(true);
        consP.setVisible(true);
        if (consP.getCodigo() != 0)
        {
            pc.buscaProduto(consP.getCodigo());
            txtProduto.setText(pc.getProd().getNome());
            txtEstoqueP.setText(pc.getProd().getNome());
            txtEstoqueP.setText(""+pc.getProd().getQtd());
            txtReservadoP.setText(""+pc.qtdReservaP());
            consP.dispose();
        }
        else
        {
            consP.dispose();
        }
    }//GEN-LAST:event_btnlocProdutoActionPerformed

    private void btnaddFolhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddFolhaActionPerformed
       CadastroFolha frm = new CadastroFolha(null, true);
       frm.setTitle("Cadastro Folha");
       frm.setVisible(true);
    }//GEN-LAST:event_btnaddFolhaActionPerformed

    private void btnlocFolhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlocFolhaActionPerformed
        ConsultaPadrao consFolha = new ConsultaPadrao(null, true);
        String[] vet = new String[2];
        vet[0] = "Tamanho";
        vet[1] = "Descrição";
        consFolha.configuraOpcoes(vet, 2, 0, "AFolha", false);
        consFolha.verificaconsulta(true);
        consFolha.setVisible(true);
        if (consFolha.getCodigo() != 0)
        {
            pc.buscaFolha(consFolha.getCodigo());
            txtFolha.setText(pc.getF().getTamanho()+ "/" +pc.getF().getDescricao());
            txtEstoqueF.setText(""+pc.getF().getQtd());
            txtReservadoF.setText(""+pc.qtdReservaF());
            consFolha.dispose();
        }
        else
        {
            consFolha.dispose();
        }
    }//GEN-LAST:event_btnlocFolhaActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        ReadOnlyTableModel model = (ReadOnlyTableModel) jTable2.getModel();
        cbStatus.setSelectedItem(model.getValueAt(jTable2.getSelectedRow(), 2)); 
        if(model.getValueAt(jTable2.getSelectedRow(), 2).equals("Aguardando"))
        {
            sc.Edity(jPanel3.getComponents());
            sc.HabilityComponents(jPanel4.getComponents(), true);
            jPanel3.setEnabled(false);
            sc.HabilityComponents(jPanel1.getComponents(), false);
        }
        else
        {
            jTable3.setEnabled(true);
            btnCancelar.setEnabled(true);
            btnGravar.setEnabled(true);
        }
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        sc.limpar(jPanel4.getComponents());
        sc.limpar(jPanel2.getComponents());
        sc.Initialize(jPanel3.getComponents());
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void rbClienteOP2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbClienteOP2MouseClicked
        if(rbClienteOP2.isSelected())
        {
            sc.limparTabela(jTable1);
            pc.carregarListaCliente(rbClienteOP2.isSelected() ? 1 : 2, txtFiltro.getText(), jTable1);
            //rbClienteOP3.setSelected(false);
            sc.limparTabela(jTable2);
            rbPedidoOP3.setSelected(true);
            rbPedidoOP2.setSelected(false);
        }
    }//GEN-LAST:event_rbClienteOP2MouseClicked

    private void rbClienteOP3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbClienteOP3MouseClicked
        if(rbClienteOP3.isSelected())
        {
            sc.limparTabela(jTable1);
            pc.carregarListaCliente(rbClienteOP3.isSelected() ? 2 : 1, txtFiltro.getText(), jTable1);
            //rbClienteOP2.setSelected(false);
            sc.limparTabela(jTable2);
            rbPedidoOP3.setSelected(true);
            rbPedidoOP2.setSelected(false);
        }
    }//GEN-LAST:event_rbClienteOP3MouseClicked

    private void rbPedidoOP3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbPedidoOP3MouseClicked
        if(rbPedidoOP3.isSelected())
        {
            //Jtable2 更新  OK
            //jTable2.removeAll();
            sc.limparTabela(jTable2);
            ReadOnlyTableModel model = (ReadOnlyTableModel) jTable1.getModel();
            pc.carregarListaPedido(2, jTable2, Integer.parseInt(String.valueOf(model.getValueAt(jTable1.getSelectedRow(), 2))));
            //rbPedidoOP2.setSelected(false);
        }
    }//GEN-LAST:event_rbPedidoOP3MouseClicked

    private void rbPedidoOP2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbPedidoOP2MouseClicked
        if(rbPedidoOP2.isSelected())
        {
            //Jtable2 更新  OK
            sc.limparTabela(jTable2);
            ReadOnlyTableModel model = (ReadOnlyTableModel) jTable1.getModel();
            pc.carregarListaPedido(1, jTable2, Integer.parseInt(String.valueOf(model.getValueAt(jTable1.getSelectedRow(), 2))));
            //rbPedidoOP3.setSelected(false);
        }
    }//GEN-LAST:event_rbPedidoOP2MouseClicked

    private void txtFiltroFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFiltroFocusGained
        txtFiltro.setText("");
    }//GEN-LAST:event_txtFiltroFocusGained

    private void txtFiltroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFiltroFocusLost
        if(txtFiltro.getText().equals("") || txtFiltro.getText().equals("Nome Cliente ou Numero pedido"))
        {
            txtFiltro.setText("Nome Cliente ou Numero pedido");
        }
        sc.limparTabela(jTable1);
        pc.carregarListaCliente(rbClienteOP2.isSelected() ? 1 : 2, txtFiltro.getText(), jTable1);
    }//GEN-LAST:event_txtFiltroFocusLost

    private void btnGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGravarActionPerformed
        if(m.Pergunta("Confirma a Gravação?", "Atenção") == JOptionPane.YES_OPTION)
        {
            switch(pc.atualizaProduto(cbStatus.getSelectedIndex()+1, txtFuncionario.getText()))
            {
                case 1: m.InformationMessage("A producao ja existe itens, favor atualize o estoque utilizando o AjustarEstoqueProduto ou AjustarEstoqueFolha!", "Atenção"); break;
                case 2: m.InformationMessage("Informe o Funcionário!", "Atenção"); btnlocFuncionario.requestFocus(); break;
                default:
                    ReadOnlyTableModel model = (ReadOnlyTableModel) jTable2.getModel();
                    if(pc.Atualizar(Integer.parseInt(String.valueOf(model.getValueAt(jTable2.getSelectedRow(), 0)))))
                    {
                        if(cbStatus.getSelectedIndex() == 0)
                            pc.atualizaItens(Integer.parseInt(String.valueOf(model.getValueAt(jTable2.getSelectedRow(), 0))));
                        m.InformationMessage("Atualizado com sucesso", "");
                        sc.limpar(jPanel4.getComponents());
                        sc.limpar(jPanel2.getComponents());
                        sc.limparTabela(jTable3);
                        sc.limparTabela(jTable2);
                        ReadOnlyTableModel model2 = (ReadOnlyTableModel) jTable1.getModel();
                        int i = jTable1.getSelectedRow();
                        pc.carregarListaPedido(2, jTable2, Integer.valueOf(String.valueOf(model2.getValueAt(i, 2))));
                        if(jTable2.getRowCount() > 0)
                        {
                            sc.HabilityComponents(jPanel2.getComponents(), true);
                            sc.HabilityComponents(jPanel4.getComponents(), false);
                        }
                        else
                        {
                            pc.carregarListaCliente(rbClienteOP2.isSelected() ? 1 : 2, txtFiltro.getText(), jTable1);
                            sc.Alter(jPanel3.getComponents());
                            sc.HabilityComponents(jPanel2.getComponents(), false);
                            sc.HabilityComponents(jPanel4.getComponents(), false);
                        }
                    }
                    else
                    {
                        m.ErroMessage("ERRO ao Gravar!", "ERRO");
                    }
            }
        }
    }//GEN-LAST:event_btnGravarActionPerformed

    private void btnremoveAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnremoveAllActionPerformed
        jTable3.removeAll();
        sc.limparTabela(jTable3);
        pc.limpaLista();
    }//GEN-LAST:event_btnremoveAllActionPerformed

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
        switch(pc.varidarAddItem(txtProduto.getText(), txtFolha.getText(), txtQtdP.getText(), txtQtdF.getText(), txtReservadoP.getText(), txtReservadoF.getText(), jTable3))
        {
            case 1: m.InformationMessage("Informe o produto ou/e folha!", "Atenção"); btnlocProduto.requestFocus(); break;
            case 2: m.InformationMessage("Informe a quantidade de Produto", "Atenção"); txtQtdP.requestFocus(); break;
            case 3: m.InformationMessage("A quantidade de produto informado é maior do que esta reservado e no estoque!", "Atenção"); txtQtdP.requestFocus(); break;
            case 4: m.InformationMessage("Informe a quantidade de Folha", "Atenção"); txtQtdF.requestFocus(); break;
            case 5: m.InformationMessage("A quantidade de folha informada é maior do que esta reservado e no estoque!", "Atenção"); txtQtdF.requestFocus(); break;
            case 6: m.InformationMessage("Produto ja esta inselido!", "Atenção"); break;
            case 7: m.InformationMessage("Folha ja inselido!", "Atenção"); break;
            default:
                pc.addTabela(jTable3, !txtFolha.getText().equals(""), !txtProduto.getText().equals(""));
                txtFolha.setText("");
                txtProduto.setText("");
                txtQtdF.setText("");
                txtQtdP.setText("");
                txtEstoqueF.setText("");
                txtEstoqueP.setText("");
                txtReservadoF.setText("");
                txtReservadoP.setText("");
        }
    }//GEN-LAST:event_btnaddActionPerformed

    private void rbClienteOP3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbClienteOP3ActionPerformed
        rbClienteOP2.setSelected(false);
        sc.limparTabela(jTable1);
    }//GEN-LAST:event_rbClienteOP3ActionPerformed

    private void rbClienteOP2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbClienteOP2ActionPerformed
        rbClienteOP3.setSelected(false);
        sc.limparTabela(jTable1);
    }//GEN-LAST:event_rbClienteOP2ActionPerformed

    private void rbPedidoOP3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbPedidoOP3ActionPerformed
        sc.limparTabela(jTable2);
        rbPedidoOP2.setSelected(false);
    }//GEN-LAST:event_rbPedidoOP3ActionPerformed

    private void rbPedidoOP2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbPedidoOP2ActionPerformed
        sc.limparTabela(jTable2);
        rbPedidoOP3.setSelected(false);
    }//GEN-LAST:event_rbPedidoOP2ActionPerformed

    private void txtFiltroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFiltroKeyPressed
       if(evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER)
       {
           txtFiltroFocusLost(null);
       }
    }//GEN-LAST:event_txtFiltroKeyPressed

    private void btnexcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexcluirActionPerformed
        if(m.Pergunta("Deseja remover o item selecionado?", "Atenção") == JOptionPane.YES_OPTION)
        {
            pc.excluirItem(jTable3, jTable3.getSelectedRow());
            m.InformationMessage("Removido com sucesso!", "Atenção");
        }
    }//GEN-LAST:event_btnexcluirActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGravar;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btnaddFolha;
    private javax.swing.JButton btnaddFuncionario;
    private javax.swing.JButton btnaddProduto;
    private javax.swing.JButton btnexcluir;
    private javax.swing.JButton btnlocFolha;
    private javax.swing.JButton btnlocFuncionario;
    private javax.swing.JButton btnlocProduto;
    private javax.swing.JButton btnremoveAll;
    private javax.swing.JComboBox<String> cbStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JRadioButton rbClienteOP2;
    private javax.swing.JRadioButton rbClienteOP3;
    private javax.swing.JRadioButton rbPedidoOP2;
    private javax.swing.JRadioButton rbPedidoOP3;
    private javax.swing.JTextField txtEstoqueF;
    private javax.swing.JTextField txtEstoqueP;
    private javax.swing.JTextField txtFiltro;
    private javax.swing.JTextField txtFolha;
    private javax.swing.JTextField txtFuncionario;
    private javax.swing.JTextArea txtOBS;
    private javax.swing.JTextField txtProduto;
    private javax.swing.JTextField txtQtdF;
    private javax.swing.JTextField txtQtdP;
    private javax.swing.JTextField txtReservadoF;
    private javax.swing.JTextField txtReservadoP;
    // End of variables declaration//GEN-END:variables
}
